// Code generated by cmd/gen-arabic-table. DO NOT EDIT.
// Source: ArabicShaping.txt and Blocks.txt from https://unicode.org/Public/UCD/latest/ucd/
//
// HarfBuzz equivalent: hb-ot-shaper-arabic-table.hh

package ot

// Short aliases for joining types (used only in table below)
const (
	_U  = joiningTypeU
	_L  = joiningTypeL
	_R  = joiningTypeR
	_D  = joiningTypeD
	_C  = joiningTypeC
	_T  = joiningTypeT
	_X  = joiningTypeX
	_A  = joiningGroupAlaph
	_DR = joiningGroupDalathRish
)

// joiningTable is the unified Arabic joining table.
// HarfBuzz equivalent: joining_table[] in hb-ot-shaper-arabic-table.hh
var joiningTable = []JoiningType{

	// offset 0x0600 = 0

	// Arabic
	/* 0600 */ _U, _U, _U, _U, _U, _U, _X, _X, _U, _X, _X, _U, _X, _X, _X, _X,
	/* 0610 */ _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X,
	/* 0620 */ _D, _U, _R, _R, _R, _R, _D, _R, _D, _R, _D, _D, _D, _D, _D, _R,
	/* 0630 */ _R, _R, _R, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D,
	/* 0640 */ _C, _D, _D, _D, _D, _D, _D, _D, _R, _D, _D, _X, _X, _X, _X, _X,
	/* 0650 */ _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X,
	/* 0660 */ _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _D, _D,
	/* 0670 */ _X, _R, _R, _R, _U, _R, _R, _R, _D, _D, _D, _D, _D, _D, _D, _D,
	/* 0680 */ _D, _D, _D, _D, _D, _D, _D, _D, _R, _R, _R, _R, _R, _R, _R, _R,
	/* 0690 */ _R, _R, _R, _R, _R, _R, _R, _R, _R, _R, _D, _D, _D, _D, _D, _D,
	/* 06A0 */ _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D,
	/* 06B0 */ _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D,
	/* 06C0 */ _R, _D, _D, _R, _R, _R, _R, _R, _R, _R, _R, _R, _D, _R, _D, _R,
	/* 06D0 */ _D, _D, _R, _R, _X, _R, _X, _X, _X, _X, _X, _X, _X, _U, _X, _X,
	/* 06E0 */ _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _R, _R,
	/* 06F0 */ _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _D, _D, _D, _X, _X, _D,

	// Syriac
	/* 0700 */ _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _T,
	/* 0710 */ _A, _X, _D, _D, _D, _DR, _DR, _R, _R, _R, _D, _D, _D, _D, _R, _D,
	/* 0720 */ _D, _D, _D, _D, _D, _D, _D, _D, _R, _D, _DR, _D, _R, _D, _D, _DR,
	/* 0730 */ _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X,
	/* 0740 */ _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _R, _D, _D,

	// Arabic Supplement
	/* 0750 */ _D, _D, _D, _D, _D, _D, _D, _D, _D, _R, _R, _R, _D, _D, _D, _D,
	/* 0760 */ _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _R, _R, _D, _D, _D,
	/* 0770 */ _D, _R, _D, _R, _R, _D, _D, _D, _R, _R, _D, _D, _D, _D, _D, _D,

	// Thaana
	/* 0780 */ _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X,
	/* 0790 */ _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X,
	/* 07A0 */ _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X,
	/* 07B0 */ _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X,

	// NKo
	/* 07C0 */ _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _D, _D, _D, _D, _D, _D,
	/* 07D0 */ _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D,
	/* 07E0 */ _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _X, _X, _X, _X, _X,
	/* 07F0 */ _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _C, _X, _X, _X, _X, _X,

	// Samaritan
	/* 0800 */ _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X,
	/* 0810 */ _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X,
	/* 0820 */ _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X,
	/* 0830 */ _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X,

	// Mandaic
	/* 0840 */ _R, _D, _D, _D, _D, _D, _R, _R, _D, _R, _D, _D, _D, _D, _D, _D,
	/* 0850 */ _D, _D, _D, _D, _R, _D, _R, _R, _R, _X, _X, _X, _X, _X, _X, _X,

	// Syriac Supplement
	/* 0860 */ _D, _U, _D, _D, _D, _D, _U, _R, _D, _R, _R, _X, _X, _X, _X, _X,

	// Arabic Extended-B
	/* 0870 */ _R, _R, _R, _R, _R, _R, _R, _R, _R, _R, _R, _R, _R, _R, _R, _R,
	/* 0880 */ _R, _R, _R, _C, _C, _C, _D, _U, _U, _D, _D, _D, _D, _D, _R, _D,
	/* 0890 */ _U, _U, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X,

	// Arabic Extended-A
	/* 08A0 */ _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _R, _R, _R, _U, _R, _D,
	/* 08B0 */ _D, _R, _R, _D, _D, _D, _D, _D, _D, _R, _D, _D, _D, _D, _D, _D,
	/* 08C0 */ _D, _D, _D, _D, _D, _D, _D, _D, _D, _X, _X, _X, _X, _X, _X, _X,
	/* 08D0 */ _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X,
	/* 08E0 */ _X, _X, _U,

	// offset 0x1806 = 739

	// Mongolian
	/* 1806 */ _U, _D, _X, _X, _C, _X, _X, _X, _U, _X,
	/* 1810 */ _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X,
	/* 1820 */ _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D,
	/* 1830 */ _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D,
	/* 1840 */ _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D,
	/* 1850 */ _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D,
	/* 1860 */ _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D,
	/* 1870 */ _D, _D, _D, _D, _D, _D, _D, _D, _D, _X, _X, _X, _X, _X, _X, _X,
	/* 1880 */ _U, _U, _U, _U, _U, _T, _T, _D, _D, _D, _D, _D, _D, _D, _D, _D,
	/* 1890 */ _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D,
	/* 18A0 */ _D, _D, _D, _D, _D, _D, _D, _D, _D, _X, _D,

	// offset 0x200C = 904

	// General Punctuation
	/* 200C */ _U, _C, _X, _X,
	/* 2010 */ _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X,
	/* 2020 */ _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _U,
	/* 2030 */ _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X,
	/* 2040 */ _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X,
	/* 2050 */ _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X,
	/* 2060 */ _X, _X, _X, _X, _X, _X, _U, _U, _U, _U,

	// offset 0xA840 = 998

	// Phags-pa
	/* A840 */ _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D,
	/* A850 */ _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D,
	/* A860 */ _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D,
	/* A870 */ _D, _D, _L, _U,

	// offset 0x10AC0 = 1050

	// Manichaean
	/* 10AC0 */ _D, _D, _D, _D, _D, _R, _U, _R, _U, _R, _R, _U, _U, _L, _R, _R,
	/* 10AD0 */ _R, _R, _R, _D, _D, _D, _D, _L, _D, _D, _D, _D, _D, _R, _D, _D,
	/* 10AE0 */ _D, _R, _U, _U, _R, _X, _X, _X, _X, _X, _X, _D, _D, _D, _D, _R,

	// offset 0x10B80 = 1098

	// Psalter Pahlavi
	/* 10B80 */ _D, _R, _D, _R, _R, _R, _D, _D, _D, _R, _D, _D, _R, _D, _R, _R,
	/* 10B90 */ _D, _R, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X,
	/* 10BA0 */ _X, _X, _X, _X, _X, _X, _X, _X, _X, _R, _R, _R, _R, _D, _D, _U,

	// offset 0x10D00 = 1146

	// Hanifi Rohingya
	/* 10D00 */ _L, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D,
	/* 10D10 */ _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D,
	/* 10D20 */ _D, _D, _R, _D,

	// offset 0x10EC2 = 1182

	// Arabic Extended-C
	/* 10EC2 */ _R, _D, _D, _X, _D, _D,

	// offset 0x10F30 = 1188

	// Sogdian
	/* 10F30 */ _D, _D, _D, _R, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D,
	/* 10F40 */ _D, _D, _D, _D, _D, _U, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X,
	/* 10F50 */ _X, _D, _D, _D, _R, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X,
	/* 10F60 */ _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X,

	// Old Uyghur
	/* 10F70 */ _D, _D, _D, _D, _R, _R, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D,
	/* 10F80 */ _D, _D, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X,
	/* 10F90 */ _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X,
	/* 10FA0 */ _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X,

	// Chorasmian
	/* 10FB0 */ _D, _U, _D, _D, _R, _R, _R, _U, _D, _R, _R, _D, _D, _R, _D, _D,
	/* 10FC0 */ _U, _D, _R, _R, _D, _U, _U, _U, _U, _R, _D, _L,

	// offset 0x110BD = 1344

	// Kaithi
	/* 110BD */ _U, _X, _X,
	/* 110C0 */ _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _U,

	// offset 0x1E900 = 1361

	// Adlam
	/* 1E900 */ _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D,
	/* 1E910 */ _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D,
	/* 1E920 */ _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D,
	/* 1E930 */ _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D, _D,
	/* 1E940 */ _D, _D, _D, _D, _X, _X, _X, _X, _X, _X, _X, _T,
}

// Offset constants for joiningTable ranges
const (
	joiningOffset0x0600  = 0
	joiningOffset0x1806  = 739
	joiningOffset0x200C  = 904
	joiningOffset0xA840  = 998
	joiningOffset0x10AC0 = 1050
	joiningOffset0x10B80 = 1098
	joiningOffset0x10D00 = 1146
	joiningOffset0x10EC2 = 1182
	joiningOffset0x10F30 = 1188
	joiningOffset0x110BD = 1344
	joiningOffset0x1E900 = 1361
)

// joiningType returns the Arabic joining type for a codepoint from the table.
// Returns joiningTypeX for codepoints not in the table.
// HarfBuzz equivalent: joining_type() in hb-ot-shaper-arabic-table.hh
func joiningType(u Codepoint) JoiningType {
	switch u >> 12 {
	case 0x0:
		if u >= 0x0600 && u <= 0x08E2 {
			return joiningTable[u-0x0600+joiningOffset0x0600]
		}
	case 0x1:
		if u >= 0x1806 && u <= 0x18AA {
			return joiningTable[u-0x1806+joiningOffset0x1806]
		}
	case 0x2:
		if u >= 0x200C && u <= 0x2069 {
			return joiningTable[u-0x200C+joiningOffset0x200C]
		}
	case 0xA:
		if u >= 0xA840 && u <= 0xA873 {
			return joiningTable[u-0xA840+joiningOffset0xA840]
		}
	case 0x10:
		if u >= 0x10AC0 && u <= 0x10AEF {
			return joiningTable[u-0x10AC0+joiningOffset0x10AC0]
		}
		if u >= 0x10B80 && u <= 0x10BAF {
			return joiningTable[u-0x10B80+joiningOffset0x10B80]
		}
		if u >= 0x10D00 && u <= 0x10D23 {
			return joiningTable[u-0x10D00+joiningOffset0x10D00]
		}
		if u >= 0x10EC2 && u <= 0x10EC7 {
			return joiningTable[u-0x10EC2+joiningOffset0x10EC2]
		}
		if u >= 0x10F30 && u <= 0x10FCB {
			return joiningTable[u-0x10F30+joiningOffset0x10F30]
		}
	case 0x11:
		if u >= 0x110BD && u <= 0x110CD {
			return joiningTable[u-0x110BD+joiningOffset0x110BD]
		}
	case 0x1E:
		if u >= 0x1E900 && u <= 0x1E94B {
			return joiningTable[u-0x1E900+joiningOffset0x1E900]
		}
	}
	return joiningTypeX
}

// hasArabicJoining returns true if the script uses Arabic-like joining.
// HarfBuzz equivalent: has_arabic_joining() in hb-ot-shaper-arabic-joining-list.hh
// Generated from ArabicShaping.txt and Scripts.txt
func hasArabicJoining(script Tag) bool {
	switch script {
	case MakeTag('A', 'd', 'l', 'm'), // Adlam
		MakeTag('A', 'r', 'a', 'b'), // Arabic
		MakeTag('C', 'h', 'r', 's'), // Chorasmian
		MakeTag('R', 'o', 'h', 'g'), // Hanifi Rohingya
		MakeTag('M', 'a', 'n', 'd'), // Mandaic
		MakeTag('M', 'a', 'n', 'i'), // Manichaean
		MakeTag('M', 'o', 'n', 'g'), // Mongolian
		MakeTag('N', 'k', 'o', 'o'), // N'Ko
		MakeTag('O', 'u', 'g', 'r'), // Old Uyghur
		MakeTag('P', 'h', 'a', 'g'), // Phags-pa
		MakeTag('P', 'h', 'l', 'p'), // Psalter Pahlavi
		MakeTag('S', 'o', 'g', 'd'), // Sogdian
		MakeTag('S', 'y', 'r', 'c'): // Syriac
		return true
	default:
		return false
	}
}
