// Code generated by cmd/gen-ccc. DO NOT EDIT.
// Source: UnicodeData.txt from https://unicode.org/Public/UCD/latest/ucd/

package ot

// getCombiningClass returns the Unicode Canonical Combining Class for a codepoint.
// CCC 0 means the character is a starter (base character).
// Non-zero values indicate combining marks with specific ordering.
func getCombiningClass(cp Codepoint) uint8 {
	if cp >= 0x0300 && cp <= 0x036F {
		return cccBlock0300[cp-0x0300]
	}
	if cp >= 0x0591 && cp <= 0x05C7 {
		return cccBlock0591[cp-0x0591]
	}
	if cp >= 0x0610 && cp <= 0x061A {
		return cccBlock0610[cp-0x0610]
	}
	if cp >= 0x064B && cp <= 0x065F {
		return cccBlock064B[cp-0x064B]
	}
	if cp >= 0x06D6 && cp <= 0x06ED {
		return cccBlock06D6[cp-0x06D6]
	}
	if cp >= 0x0730 && cp <= 0x074A {
		return cccBlock0730[cp-0x0730]
	}
	if cp >= 0x07EB && cp <= 0x07F3 {
		return cccBlock07EB[cp-0x07EB]
	}
	if cp >= 0x0816 && cp <= 0x082D {
		return cccBlock0816[cp-0x0816]
	}
	if cp >= 0x0897 && cp <= 0x089F {
		return cccBlock0897[cp-0x0897]
	}
	if cp >= 0x08CA && cp <= 0x08FF {
		return cccBlock08CA[cp-0x08CA]
	}
	if cp >= 0x0F7A && cp <= 0x0F87 {
		return cccBlock0F7A[cp-0x0F7A]
	}
	if cp >= 0x1A75 && cp <= 0x1A7F {
		return cccBlock1A75[cp-0x1A75]
	}
	if cp >= 0x1AB0 && cp <= 0x1AEB {
		return cccBlock1AB0[cp-0x1AB0]
	}
	if cp >= 0x1B6B && cp <= 0x1B73 {
		return cccBlock1B6B[cp-0x1B6B]
	}
	if cp >= 0x1CD0 && cp <= 0x1CE8 {
		return cccBlock1CD0[cp-0x1CD0]
	}
	if cp >= 0x1DC0 && cp <= 0x1DFF {
		return cccBlock1DC0[cp-0x1DC0]
	}
	if cp >= 0x20D0 && cp <= 0x20DC {
		return cccBlock20D0[cp-0x20D0]
	}
	if cp >= 0x20E1 && cp <= 0x20F0 {
		return cccBlock20E1[cp-0x20E1]
	}
	if cp >= 0x2DE0 && cp <= 0x2DFF {
		return cccBlock2DE0[cp-0x2DE0]
	}
	if cp >= 0xA674 && cp <= 0xA67D {
		return cccBlockA674[cp-0xA674]
	}
	if cp >= 0xA8E0 && cp <= 0xA8F1 {
		return cccBlockA8E0[cp-0xA8E0]
	}
	if cp >= 0xFE20 && cp <= 0xFE2F {
		return cccBlockFE20[cp-0xFE20]
	}
	if cp >= 0x10F46 && cp <= 0x10F50 {
		return cccBlock10F46[cp-0x10F46]
	}
	if cp >= 0x11366 && cp <= 0x11374 {
		return cccBlock11366[cp-0x11366]
	}
	if cp >= 0x1D165 && cp <= 0x1D172 {
		return cccBlock1D165[cp-0x1D165]
	}
	if cp >= 0x1D17B && cp <= 0x1D18B {
		return cccBlock1D17B[cp-0x1D17B]
	}
	if cp >= 0x1E000 && cp <= 0x1E02A {
		return cccBlock1E000[cp-0x1E000]
	}
	switch cp {
	case 0x0483:
		return 230
	case 0x0484:
		return 230
	case 0x0485:
		return 230
	case 0x0486:
		return 230
	case 0x0487:
		return 230
	case 0x0670:
		return 35
	case 0x0711:
		return 36
	case 0x07FD:
		return 220
	case 0x0859:
		return 220
	case 0x085A:
		return 220
	case 0x085B:
		return 220
	case 0x093C:
		return 7
	case 0x094D:
		return 9
	case 0x0951:
		return 230
	case 0x0952:
		return 220
	case 0x0953:
		return 230
	case 0x0954:
		return 230
	case 0x09BC:
		return 7
	case 0x09CD:
		return 9
	case 0x09FE:
		return 230
	case 0x0A3C:
		return 7
	case 0x0A4D:
		return 9
	case 0x0ABC:
		return 7
	case 0x0ACD:
		return 9
	case 0x0B3C:
		return 7
	case 0x0B4D:
		return 9
	case 0x0BCD:
		return 9
	case 0x0C3C:
		return 7
	case 0x0C4D:
		return 9
	case 0x0C55:
		return 84
	case 0x0C56:
		return 91
	case 0x0CBC:
		return 7
	case 0x0CCD:
		return 9
	case 0x0D3B:
		return 9
	case 0x0D3C:
		return 9
	case 0x0D4D:
		return 9
	case 0x0DCA:
		return 9
	case 0x0E38:
		return 103
	case 0x0E39:
		return 103
	case 0x0E3A:
		return 9
	case 0x0E48:
		return 107
	case 0x0E49:
		return 107
	case 0x0E4A:
		return 107
	case 0x0E4B:
		return 107
	case 0x0EB8:
		return 118
	case 0x0EB9:
		return 118
	case 0x0EBA:
		return 9
	case 0x0EC8:
		return 122
	case 0x0EC9:
		return 122
	case 0x0ECA:
		return 122
	case 0x0ECB:
		return 122
	case 0x0F18:
		return 220
	case 0x0F19:
		return 220
	case 0x0F35:
		return 220
	case 0x0F37:
		return 220
	case 0x0F39:
		return 216
	case 0x0F71:
		return 129
	case 0x0F72:
		return 130
	case 0x0F74:
		return 132
	case 0x0FC6:
		return 220
	case 0x1037:
		return 7
	case 0x1039:
		return 9
	case 0x103A:
		return 9
	case 0x108D:
		return 220
	case 0x135D:
		return 230
	case 0x135E:
		return 230
	case 0x135F:
		return 230
	case 0x1714:
		return 9
	case 0x1715:
		return 9
	case 0x1734:
		return 9
	case 0x17D2:
		return 9
	case 0x17DD:
		return 230
	case 0x18A9:
		return 228
	case 0x1939:
		return 222
	case 0x193A:
		return 230
	case 0x193B:
		return 220
	case 0x1A17:
		return 230
	case 0x1A18:
		return 220
	case 0x1A60:
		return 9
	case 0x1B34:
		return 7
	case 0x1B44:
		return 9
	case 0x1BAA:
		return 9
	case 0x1BAB:
		return 9
	case 0x1BE6:
		return 7
	case 0x1BF2:
		return 9
	case 0x1BF3:
		return 9
	case 0x1C37:
		return 7
	case 0x1CED:
		return 220
	case 0x1CF4:
		return 230
	case 0x1CF8:
		return 230
	case 0x1CF9:
		return 230
	case 0x2CEF:
		return 230
	case 0x2CF0:
		return 230
	case 0x2CF1:
		return 230
	case 0x2D7F:
		return 9
	case 0x302A:
		return 218
	case 0x302B:
		return 228
	case 0x302C:
		return 232
	case 0x302D:
		return 222
	case 0x302E:
		return 224
	case 0x302F:
		return 224
	case 0x3099:
		return 8
	case 0x309A:
		return 8
	case 0xA66F:
		return 230
	case 0xA69E:
		return 230
	case 0xA69F:
		return 230
	case 0xA6F0:
		return 230
	case 0xA6F1:
		return 230
	case 0xA806:
		return 9
	case 0xA82C:
		return 9
	case 0xA8C4:
		return 9
	case 0xA92B:
		return 220
	case 0xA92C:
		return 220
	case 0xA92D:
		return 220
	case 0xA953:
		return 9
	case 0xA9B3:
		return 7
	case 0xA9C0:
		return 9
	case 0xAAB0:
		return 230
	case 0xAAB2:
		return 230
	case 0xAAB3:
		return 230
	case 0xAAB4:
		return 220
	case 0xAAB7:
		return 230
	case 0xAAB8:
		return 230
	case 0xAABE:
		return 230
	case 0xAABF:
		return 230
	case 0xAAC1:
		return 230
	case 0xAAF6:
		return 9
	case 0xABED:
		return 9
	case 0xFB1E:
		return 26
	case 0x101FD:
		return 220
	case 0x102E0:
		return 220
	case 0x10376:
		return 230
	case 0x10377:
		return 230
	case 0x10378:
		return 230
	case 0x10379:
		return 230
	case 0x1037A:
		return 230
	case 0x10A0D:
		return 220
	case 0x10A0F:
		return 230
	case 0x10A38:
		return 230
	case 0x10A39:
		return 1
	case 0x10A3A:
		return 220
	case 0x10A3F:
		return 9
	case 0x10AE5:
		return 230
	case 0x10AE6:
		return 220
	case 0x10D24:
		return 230
	case 0x10D25:
		return 230
	case 0x10D26:
		return 230
	case 0x10D27:
		return 230
	case 0x10D69:
		return 230
	case 0x10D6A:
		return 230
	case 0x10D6B:
		return 230
	case 0x10D6C:
		return 230
	case 0x10D6D:
		return 230
	case 0x10EAB:
		return 230
	case 0x10EAC:
		return 230
	case 0x10EFA:
		return 220
	case 0x10EFB:
		return 220
	case 0x10EFD:
		return 220
	case 0x10EFE:
		return 220
	case 0x10EFF:
		return 220
	case 0x10F82:
		return 230
	case 0x10F83:
		return 220
	case 0x10F84:
		return 230
	case 0x10F85:
		return 220
	case 0x11046:
		return 9
	case 0x11070:
		return 9
	case 0x1107F:
		return 9
	case 0x110B9:
		return 9
	case 0x110BA:
		return 7
	case 0x11100:
		return 230
	case 0x11101:
		return 230
	case 0x11102:
		return 230
	case 0x11133:
		return 9
	case 0x11134:
		return 9
	case 0x11173:
		return 7
	case 0x111C0:
		return 9
	case 0x111CA:
		return 7
	case 0x11235:
		return 9
	case 0x11236:
		return 7
	case 0x112E9:
		return 7
	case 0x112EA:
		return 9
	case 0x1133B:
		return 7
	case 0x1133C:
		return 7
	case 0x1134D:
		return 9
	case 0x113CE:
		return 9
	case 0x113CF:
		return 9
	case 0x113D0:
		return 9
	case 0x11442:
		return 9
	case 0x11446:
		return 7
	case 0x1145E:
		return 230
	case 0x114C2:
		return 9
	case 0x114C3:
		return 7
	case 0x115BF:
		return 9
	case 0x115C0:
		return 7
	case 0x1163F:
		return 9
	case 0x116B6:
		return 9
	case 0x116B7:
		return 7
	case 0x1172B:
		return 9
	case 0x11839:
		return 9
	case 0x1183A:
		return 7
	case 0x1193D:
		return 9
	case 0x1193E:
		return 9
	case 0x11943:
		return 7
	case 0x119E0:
		return 9
	case 0x11A34:
		return 9
	case 0x11A47:
		return 9
	case 0x11A99:
		return 9
	case 0x11C3F:
		return 9
	case 0x11D42:
		return 7
	case 0x11D44:
		return 9
	case 0x11D45:
		return 9
	case 0x11D97:
		return 9
	case 0x11F41:
		return 9
	case 0x11F42:
		return 9
	case 0x1612F:
		return 9
	case 0x16AF0:
		return 1
	case 0x16AF1:
		return 1
	case 0x16AF2:
		return 1
	case 0x16AF3:
		return 1
	case 0x16AF4:
		return 1
	case 0x16B30:
		return 230
	case 0x16B31:
		return 230
	case 0x16B32:
		return 230
	case 0x16B33:
		return 230
	case 0x16B34:
		return 230
	case 0x16B35:
		return 230
	case 0x16B36:
		return 230
	case 0x16FF0:
		return 6
	case 0x16FF1:
		return 6
	case 0x1BC9E:
		return 1
	case 0x1D1AA:
		return 230
	case 0x1D1AB:
		return 230
	case 0x1D1AC:
		return 230
	case 0x1D1AD:
		return 230
	case 0x1D242:
		return 230
	case 0x1D243:
		return 230
	case 0x1D244:
		return 230
	case 0x1E08F:
		return 230
	case 0x1E130:
		return 230
	case 0x1E131:
		return 230
	case 0x1E132:
		return 230
	case 0x1E133:
		return 230
	case 0x1E134:
		return 230
	case 0x1E135:
		return 230
	case 0x1E136:
		return 230
	case 0x1E2AE:
		return 230
	case 0x1E2EC:
		return 230
	case 0x1E2ED:
		return 230
	case 0x1E2EE:
		return 230
	case 0x1E2EF:
		return 230
	case 0x1E4EC:
		return 232
	case 0x1E4ED:
		return 232
	case 0x1E4EE:
		return 220
	case 0x1E4EF:
		return 230
	case 0x1E5EE:
		return 230
	case 0x1E5EF:
		return 220
	case 0x1E6E3:
		return 230
	case 0x1E6E6:
		return 230
	case 0x1E6EE:
		return 230
	case 0x1E6EF:
		return 230
	case 0x1E6F5:
		return 230
	case 0x1E8D0:
		return 220
	case 0x1E8D1:
		return 220
	case 0x1E8D2:
		return 220
	case 0x1E8D3:
		return 220
	case 0x1E8D4:
		return 220
	case 0x1E8D5:
		return 220
	case 0x1E8D6:
		return 220
	case 0x1E944:
		return 230
	case 0x1E945:
		return 230
	case 0x1E946:
		return 230
	case 0x1E947:
		return 230
	case 0x1E948:
		return 230
	case 0x1E949:
		return 230
	case 0x1E94A:
		return 7
	}
	return 0
}

var cccBlock0300 = [112]uint8{
	230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230,
	230, 230, 230, 230, 230, 232, 220, 220, 220, 220, 232, 216, 220, 220, 220, 220,
	220, 202, 202, 220, 220, 220, 220, 202, 202, 220, 220, 220, 220, 220, 220, 220,
	220, 220, 220, 220, 1, 1, 1, 1, 1, 220, 220, 220, 220, 230, 230, 230,
	230, 230, 230, 230, 230, 240, 230, 220, 220, 220, 230, 230, 230, 220, 220, 0,
	230, 230, 230, 220, 220, 220, 220, 230, 232, 220, 220, 230, 233, 234, 234, 233,
	234, 234, 233, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230,
}

var cccBlock0591 = [55]uint8{
	220, 230, 230, 230, 230, 220, 230, 230, 230, 222, 220, 230, 230, 230, 230, 230,
	230, 220, 220, 220, 220, 220, 220, 230, 230, 220, 230, 230, 222, 228, 230, 10,
	11, 12, 13, 14, 15, 16, 17, 18, 19, 19, 20, 21, 22, 0, 23, 0,
	24, 25, 0, 230, 220, 0, 18,
}

var cccBlock0610 = [11]uint8{
	230, 230, 230, 230, 230, 230, 230, 230, 30, 31, 32,
}

var cccBlock064B = [21]uint8{
	27, 28, 29, 30, 31, 32, 33, 34, 230, 230, 220, 220, 230, 230, 230, 230,
	230, 220, 230, 230, 220,
}

var cccBlock06D6 = [24]uint8{
	230, 230, 230, 230, 230, 230, 230, 0, 0, 230, 230, 230, 230, 220, 230, 0,
	0, 230, 230, 0, 220, 230, 230, 220,
}

var cccBlock0730 = [27]uint8{
	230, 220, 230, 230, 220, 230, 230, 220, 220, 220, 230, 220, 220, 230, 220, 230,
	230, 230, 220, 230, 220, 230, 220, 230, 220, 230, 230,
}

var cccBlock07EB = [9]uint8{
	230, 230, 230, 230, 230, 230, 230, 220, 230,
}

var cccBlock0816 = [24]uint8{
	230, 230, 230, 230, 0, 230, 230, 230, 230, 230, 230, 230, 230, 230, 0, 230,
	230, 230, 0, 230, 230, 230, 230, 230,
}

var cccBlock0897 = [9]uint8{
	230, 230, 220, 220, 220, 230, 230, 230, 230,
}

var cccBlock08CA = [54]uint8{
	230, 230, 230, 230, 230, 220, 220, 220, 220, 220, 230, 230, 230, 230, 230, 230,
	230, 230, 230, 230, 230, 230, 230, 230, 0, 220, 230, 230, 220, 230, 230, 220,
	230, 230, 230, 220, 220, 220, 27, 28, 29, 230, 230, 230, 220, 230, 230, 220,
	220, 230, 230, 230, 230, 230,
}

var cccBlock0F7A = [14]uint8{
	130, 130, 130, 130, 0, 0, 130, 0, 230, 230, 9, 0, 230, 230,
}

var cccBlock1A75 = [11]uint8{
	230, 230, 230, 230, 230, 230, 230, 230, 0, 0, 220,
}

var cccBlock1AB0 = [60]uint8{
	230, 230, 230, 230, 230, 220, 220, 220, 220, 220, 220, 230, 230, 220, 0, 220,
	220, 230, 230, 220, 220, 230, 230, 230, 230, 230, 220, 230, 230, 230, 230, 230,
	230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 220, 0, 0,
	230, 230, 230, 230, 230, 230, 220, 230, 230, 230, 230, 234,
}

var cccBlock1B6B = [9]uint8{
	230, 220, 230, 230, 230, 230, 230, 230, 230,
}

var cccBlock1CD0 = [25]uint8{
	230, 230, 230, 0, 1, 220, 220, 220, 220, 220, 230, 230, 220, 220, 220, 220,
	230, 0, 1, 1, 1, 1, 1, 1, 1,
}

var cccBlock1DC0 = [64]uint8{
	230, 230, 220, 230, 230, 230, 230, 230, 230, 230, 220, 230, 230, 234, 214, 220,
	202, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230,
	230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230,
	230, 230, 230, 230, 230, 230, 232, 228, 228, 220, 218, 230, 233, 220, 230, 220,
}

var cccBlock20D0 = [13]uint8{
	230, 230, 1, 1, 230, 230, 230, 230, 1, 1, 1, 230, 230,
}

var cccBlock20E1 = [16]uint8{
	230, 0, 0, 0, 1, 1, 230, 220, 230, 1, 1, 220, 220, 220, 220, 230,
}

var cccBlock2DE0 = [32]uint8{
	230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230,
	230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230,
}

var cccBlockA674 = [10]uint8{
	230, 230, 230, 230, 230, 230, 230, 230, 230, 230,
}

var cccBlockA8E0 = [18]uint8{
	230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230, 230,
	230, 230,
}

var cccBlockFE20 = [16]uint8{
	230, 230, 230, 230, 230, 230, 230, 220, 220, 220, 220, 220, 220, 220, 230, 230,
}

var cccBlock10F46 = [11]uint8{
	220, 220, 230, 230, 230, 220, 230, 220, 220, 220, 220,
}

var cccBlock11366 = [15]uint8{
	230, 230, 230, 230, 230, 230, 230, 0, 0, 0, 230, 230, 230, 230, 230,
}

var cccBlock1D165 = [14]uint8{
	216, 216, 1, 1, 1, 0, 0, 0, 226, 216, 216, 216, 216, 216,
}

var cccBlock1D17B = [17]uint8{
	220, 220, 220, 220, 220, 220, 220, 220, 0, 0, 230, 230, 230, 230, 230, 220,
	220,
}

var cccBlock1E000 = [43]uint8{
	230, 230, 230, 230, 230, 230, 230, 0, 230, 230, 230, 230, 230, 230, 230, 230,
	230, 230, 230, 230, 230, 230, 230, 230, 230, 0, 0, 230, 230, 230, 230, 230,
	230, 230, 0, 230, 230, 0, 230, 230, 230, 230, 230,
}
