// Code generated by cmd/gen-emoji-table. DO NOT EDIT.
// Source: emoji-data.txt from https://www.unicode.org/Public/UCD/latest/ucd/emoji/
//
// HarfBuzz equivalent: hb-unicode-emoji-table.hh

package ot

// isExtendedPictographic returns true if the codepoint is an Extended_Pictographic.
// Extended_Pictographic is used for emoji sequences (ZWJ sequences, etc.).
// HarfBuzz equivalent: _hb_emoji_is_Extended_Pictographic()
func isExtendedPictographic(cp Codepoint) bool {
	switch cp >> 8 {
	case 0x00: // U+0000-U+00FF
		if cp == 0x00A9 {
			return true
		}
		if cp == 0x00AE {
			return true
		}
	case 0x20: // U+2000-U+20FF
		if cp == 0x203C {
			return true
		}
		if cp == 0x2049 {
			return true
		}
	case 0x21: // U+2100-U+21FF
		if cp == 0x2122 {
			return true
		}
		if cp == 0x2139 {
			return true
		}
		if cp >= 0x2194 && cp <= 0x2199 {
			return true
		}
		if cp >= 0x21A9 && cp <= 0x21AA {
			return true
		}
	case 0x23: // U+2300-U+23FF
		if cp >= 0x231A && cp <= 0x231B {
			return true
		}
		if cp == 0x2328 {
			return true
		}
		if cp == 0x23CF {
			return true
		}
		if cp >= 0x23E9 && cp <= 0x23F3 {
			return true
		}
		if cp >= 0x23F8 && cp <= 0x23FA {
			return true
		}
	case 0x24: // U+2400-U+24FF
		if cp == 0x24C2 {
			return true
		}
	case 0x25: // U+2500-U+25FF
		if cp >= 0x25AA && cp <= 0x25AB {
			return true
		}
		if cp == 0x25B6 {
			return true
		}
		if cp == 0x25C0 {
			return true
		}
		if cp >= 0x25FB && cp <= 0x25FE {
			return true
		}
	case 0x26: // U+2600-U+26FF
		if cp >= 0x2600 && cp <= 0x2604 {
			return true
		}
		if cp == 0x260E {
			return true
		}
		if cp == 0x2611 {
			return true
		}
		if cp >= 0x2614 && cp <= 0x2615 {
			return true
		}
		if cp == 0x2618 {
			return true
		}
		if cp == 0x261D {
			return true
		}
		if cp == 0x2620 {
			return true
		}
		if cp >= 0x2622 && cp <= 0x2623 {
			return true
		}
		if cp == 0x2626 {
			return true
		}
		if cp == 0x262A {
			return true
		}
		if cp >= 0x262E && cp <= 0x262F {
			return true
		}
		if cp >= 0x2638 && cp <= 0x263A {
			return true
		}
		if cp == 0x2640 {
			return true
		}
		if cp == 0x2642 {
			return true
		}
		if cp >= 0x2648 && cp <= 0x2653 {
			return true
		}
		if cp >= 0x265F && cp <= 0x2660 {
			return true
		}
		if cp == 0x2663 {
			return true
		}
		if cp >= 0x2665 && cp <= 0x2666 {
			return true
		}
		if cp == 0x2668 {
			return true
		}
		if cp == 0x267B {
			return true
		}
		if cp >= 0x267E && cp <= 0x267F {
			return true
		}
		if cp >= 0x2692 && cp <= 0x2697 {
			return true
		}
		if cp == 0x2699 {
			return true
		}
		if cp >= 0x269B && cp <= 0x269C {
			return true
		}
		if cp >= 0x26A0 && cp <= 0x26A1 {
			return true
		}
		if cp == 0x26A7 {
			return true
		}
		if cp >= 0x26AA && cp <= 0x26AB {
			return true
		}
		if cp >= 0x26B0 && cp <= 0x26B1 {
			return true
		}
		if cp >= 0x26BD && cp <= 0x26BE {
			return true
		}
		if cp >= 0x26C4 && cp <= 0x26C5 {
			return true
		}
		if cp == 0x26C8 {
			return true
		}
		if cp >= 0x26CE && cp <= 0x26CF {
			return true
		}
		if cp == 0x26D1 {
			return true
		}
		if cp >= 0x26D3 && cp <= 0x26D4 {
			return true
		}
		if cp >= 0x26E9 && cp <= 0x26EA {
			return true
		}
		if cp >= 0x26F0 && cp <= 0x26F5 {
			return true
		}
		if cp >= 0x26F7 && cp <= 0x26FA {
			return true
		}
		if cp == 0x26FD {
			return true
		}
	case 0x27: // U+2700-U+27FF
		if cp == 0x2702 {
			return true
		}
		if cp == 0x2705 {
			return true
		}
		if cp >= 0x2708 && cp <= 0x270D {
			return true
		}
		if cp == 0x270F {
			return true
		}
		if cp == 0x2712 {
			return true
		}
		if cp == 0x2714 {
			return true
		}
		if cp == 0x2716 {
			return true
		}
		if cp == 0x271D {
			return true
		}
		if cp == 0x2721 {
			return true
		}
		if cp == 0x2728 {
			return true
		}
		if cp >= 0x2733 && cp <= 0x2734 {
			return true
		}
		if cp == 0x2744 {
			return true
		}
		if cp == 0x2747 {
			return true
		}
		if cp == 0x274C {
			return true
		}
		if cp == 0x274E {
			return true
		}
		if cp >= 0x2753 && cp <= 0x2755 {
			return true
		}
		if cp == 0x2757 {
			return true
		}
		if cp >= 0x2763 && cp <= 0x2764 {
			return true
		}
		if cp >= 0x2795 && cp <= 0x2797 {
			return true
		}
		if cp == 0x27A1 {
			return true
		}
		if cp == 0x27B0 {
			return true
		}
		if cp == 0x27BF {
			return true
		}
	case 0x29: // U+2900-U+29FF
		if cp >= 0x2934 && cp <= 0x2935 {
			return true
		}
	case 0x2B: // U+2B00-U+2BFF
		if cp >= 0x2B05 && cp <= 0x2B07 {
			return true
		}
		if cp >= 0x2B1B && cp <= 0x2B1C {
			return true
		}
		if cp == 0x2B50 {
			return true
		}
		if cp == 0x2B55 {
			return true
		}
	case 0x30: // U+3000-U+30FF
		if cp == 0x3030 {
			return true
		}
		if cp == 0x303D {
			return true
		}
	case 0x32: // U+3200-U+32FF
		if cp == 0x3297 {
			return true
		}
		if cp == 0x3299 {
			return true
		}
	case 0x1F0: // U+1F000-U+1F0FF
		if cp == 0x1F004 {
			return true
		}
		if cp >= 0x1F02C && cp <= 0x1F02F {
			return true
		}
		if cp >= 0x1F094 && cp <= 0x1F09F {
			return true
		}
		if cp >= 0x1F0AF && cp <= 0x1F0B0 {
			return true
		}
		if cp == 0x1F0C0 {
			return true
		}
		if cp >= 0x1F0CF && cp <= 0x1F0D0 {
			return true
		}
		if cp >= 0x1F0F6 && cp <= 0x1F0FF {
			return true
		}
	case 0x1F1: // U+1F100-U+1F1FF
		if cp >= 0x1F170 && cp <= 0x1F171 {
			return true
		}
		if cp >= 0x1F17E && cp <= 0x1F17F {
			return true
		}
		if cp == 0x1F18E {
			return true
		}
		if cp >= 0x1F191 && cp <= 0x1F19A {
			return true
		}
		if cp >= 0x1F1AE && cp <= 0x1F1E5 {
			return true
		}
	case 0x1F2: // U+1F200-U+1F2FF
		if cp >= 0x1F201 && cp <= 0x1F20F {
			return true
		}
		if cp == 0x1F21A {
			return true
		}
		if cp == 0x1F22F {
			return true
		}
		if cp >= 0x1F232 && cp <= 0x1F23A {
			return true
		}
		if cp >= 0x1F23C && cp <= 0x1F23F {
			return true
		}
		if cp >= 0x1F249 && cp <= 0x1F25F {
			return true
		}
		if cp >= 0x1F266 && cp <= 0x1F2FF {
			return true
		}
	case 0x1F3: // U+1F300-U+1F3FF
		if cp >= 0x1F300 && cp <= 0x1F321 {
			return true
		}
		if cp >= 0x1F324 && cp <= 0x1F393 {
			return true
		}
		if cp >= 0x1F396 && cp <= 0x1F397 {
			return true
		}
		if cp >= 0x1F399 && cp <= 0x1F39B {
			return true
		}
		if cp >= 0x1F39E && cp <= 0x1F3F0 {
			return true
		}
		if cp >= 0x1F3F3 && cp <= 0x1F3F5 {
			return true
		}
		if cp >= 0x1F3F7 && cp <= 0x1F3FA {
			return true
		}
	case 0x1F4: // U+1F400-U+1F4FF
		if cp >= 0x1F400 && cp <= 0x1F4FD {
			return true
		}
		if cp == 0x1F4FF {
			return true
		}
	case 0x1F5: // U+1F500-U+1F5FF
		if cp >= 0x1F500 && cp <= 0x1F53D {
			return true
		}
		if cp >= 0x1F549 && cp <= 0x1F54E {
			return true
		}
		if cp >= 0x1F550 && cp <= 0x1F567 {
			return true
		}
		if cp >= 0x1F56F && cp <= 0x1F570 {
			return true
		}
		if cp >= 0x1F573 && cp <= 0x1F57A {
			return true
		}
		if cp == 0x1F587 {
			return true
		}
		if cp >= 0x1F58A && cp <= 0x1F58D {
			return true
		}
		if cp == 0x1F590 {
			return true
		}
		if cp >= 0x1F595 && cp <= 0x1F596 {
			return true
		}
		if cp >= 0x1F5A4 && cp <= 0x1F5A5 {
			return true
		}
		if cp == 0x1F5A8 {
			return true
		}
		if cp >= 0x1F5B1 && cp <= 0x1F5B2 {
			return true
		}
		if cp == 0x1F5BC {
			return true
		}
		if cp >= 0x1F5C2 && cp <= 0x1F5C4 {
			return true
		}
		if cp >= 0x1F5D1 && cp <= 0x1F5D3 {
			return true
		}
		if cp >= 0x1F5DC && cp <= 0x1F5DE {
			return true
		}
		if cp == 0x1F5E1 {
			return true
		}
		if cp == 0x1F5E3 {
			return true
		}
		if cp == 0x1F5E8 {
			return true
		}
		if cp == 0x1F5EF {
			return true
		}
		if cp == 0x1F5F3 {
			return true
		}
		if cp >= 0x1F5FA && cp <= 0x1F5FF {
			return true
		}
	case 0x1F6: // U+1F600-U+1F6FF
		if cp >= 0x1F600 && cp <= 0x1F64F {
			return true
		}
		if cp >= 0x1F680 && cp <= 0x1F6C5 {
			return true
		}
		if cp >= 0x1F6CB && cp <= 0x1F6D2 {
			return true
		}
		if cp >= 0x1F6D5 && cp <= 0x1F6E5 {
			return true
		}
		if cp == 0x1F6E9 {
			return true
		}
		if cp >= 0x1F6EB && cp <= 0x1F6F0 {
			return true
		}
		if cp >= 0x1F6F3 && cp <= 0x1F6FF {
			return true
		}
	case 0x1F7: // U+1F700-U+1F7FF
		if cp >= 0x1F7DA && cp <= 0x1F7FF {
			return true
		}
	case 0x1F8: // U+1F800-U+1F8FF
		if cp >= 0x1F80C && cp <= 0x1F80F {
			return true
		}
		if cp >= 0x1F848 && cp <= 0x1F84F {
			return true
		}
		if cp >= 0x1F85A && cp <= 0x1F85F {
			return true
		}
		if cp >= 0x1F888 && cp <= 0x1F88F {
			return true
		}
		if cp >= 0x1F8AE && cp <= 0x1F8AF {
			return true
		}
		if cp >= 0x1F8BC && cp <= 0x1F8BF {
			return true
		}
		if cp >= 0x1F8C2 && cp <= 0x1F8CF {
			return true
		}
		if cp >= 0x1F8D9 && cp <= 0x1F8FF {
			return true
		}
	case 0x1F9: // U+1F900-U+1F9FF
		if cp >= 0x1F90C && cp <= 0x1F93A {
			return true
		}
		if cp >= 0x1F93C && cp <= 0x1F945 {
			return true
		}
		if cp >= 0x1F947 && cp <= 0x1F9FF {
			return true
		}
	case 0x1FA: // U+1FA00-U+1FAFF
		if cp >= 0x1FA58 && cp <= 0x1FA5F {
			return true
		}
		if cp >= 0x1FA6E && cp <= 0x1FAFF {
			return true
		}
	case 0x1FC: // U+1FC00-U+1FCFF
		if cp >= 0x1FC00 && cp <= 0x1FCFF {
			return true
		}
	case 0x1FD: // U+1FD00-U+1FDFF
		if cp >= 0x1FD00 && cp <= 0x1FDFF {
			return true
		}
	case 0x1FE: // U+1FE00-U+1FEFF
		if cp >= 0x1FE00 && cp <= 0x1FEFF {
			return true
		}
	case 0x1FF: // U+1FF00-U+1FFFF
		if cp >= 0x1FF00 && cp <= 0x1FFFD {
			return true
		}
	}
	return false
}

// extendedPictographicRanges contains all Extended_Pictographic ranges.
// This can be used for binary search if needed.
var extendedPictographicRanges = [][2]Codepoint{
	{0x00A9, 0x00A9},
	{0x00AE, 0x00AE},
	{0x203C, 0x203C},
	{0x2049, 0x2049},
	{0x2122, 0x2122},
	{0x2139, 0x2139},
	{0x2194, 0x2199},
	{0x21A9, 0x21AA},
	{0x231A, 0x231B},
	{0x2328, 0x2328},
	{0x23CF, 0x23CF},
	{0x23E9, 0x23F3},
	{0x23F8, 0x23FA},
	{0x24C2, 0x24C2},
	{0x25AA, 0x25AB},
	{0x25B6, 0x25B6},
	{0x25C0, 0x25C0},
	{0x25FB, 0x25FE},
	{0x2600, 0x2604},
	{0x260E, 0x260E},
	{0x2611, 0x2611},
	{0x2614, 0x2615},
	{0x2618, 0x2618},
	{0x261D, 0x261D},
	{0x2620, 0x2620},
	{0x2622, 0x2623},
	{0x2626, 0x2626},
	{0x262A, 0x262A},
	{0x262E, 0x262F},
	{0x2638, 0x263A},
	{0x2640, 0x2640},
	{0x2642, 0x2642},
	{0x2648, 0x2653},
	{0x265F, 0x2660},
	{0x2663, 0x2663},
	{0x2665, 0x2666},
	{0x2668, 0x2668},
	{0x267B, 0x267B},
	{0x267E, 0x267F},
	{0x2692, 0x2697},
	{0x2699, 0x2699},
	{0x269B, 0x269C},
	{0x26A0, 0x26A1},
	{0x26A7, 0x26A7},
	{0x26AA, 0x26AB},
	{0x26B0, 0x26B1},
	{0x26BD, 0x26BE},
	{0x26C4, 0x26C5},
	{0x26C8, 0x26C8},
	{0x26CE, 0x26CF},
	{0x26D1, 0x26D1},
	{0x26D3, 0x26D4},
	{0x26E9, 0x26EA},
	{0x26F0, 0x26F5},
	{0x26F7, 0x26FA},
	{0x26FD, 0x26FD},
	{0x2702, 0x2702},
	{0x2705, 0x2705},
	{0x2708, 0x270D},
	{0x270F, 0x270F},
	{0x2712, 0x2712},
	{0x2714, 0x2714},
	{0x2716, 0x2716},
	{0x271D, 0x271D},
	{0x2721, 0x2721},
	{0x2728, 0x2728},
	{0x2733, 0x2734},
	{0x2744, 0x2744},
	{0x2747, 0x2747},
	{0x274C, 0x274C},
	{0x274E, 0x274E},
	{0x2753, 0x2755},
	{0x2757, 0x2757},
	{0x2763, 0x2764},
	{0x2795, 0x2797},
	{0x27A1, 0x27A1},
	{0x27B0, 0x27B0},
	{0x27BF, 0x27BF},
	{0x2934, 0x2935},
	{0x2B05, 0x2B07},
	{0x2B1B, 0x2B1C},
	{0x2B50, 0x2B50},
	{0x2B55, 0x2B55},
	{0x3030, 0x3030},
	{0x303D, 0x303D},
	{0x3297, 0x3297},
	{0x3299, 0x3299},
	{0x1F004, 0x1F004},
	{0x1F02C, 0x1F02F},
	{0x1F094, 0x1F09F},
	{0x1F0AF, 0x1F0B0},
	{0x1F0C0, 0x1F0C0},
	{0x1F0CF, 0x1F0D0},
	{0x1F0F6, 0x1F0FF},
	{0x1F170, 0x1F171},
	{0x1F17E, 0x1F17F},
	{0x1F18E, 0x1F18E},
	{0x1F191, 0x1F19A},
	{0x1F1AE, 0x1F1E5},
	{0x1F201, 0x1F20F},
	{0x1F21A, 0x1F21A},
	{0x1F22F, 0x1F22F},
	{0x1F232, 0x1F23A},
	{0x1F23C, 0x1F23F},
	{0x1F249, 0x1F25F},
	{0x1F266, 0x1F321},
	{0x1F324, 0x1F393},
	{0x1F396, 0x1F397},
	{0x1F399, 0x1F39B},
	{0x1F39E, 0x1F3F0},
	{0x1F3F3, 0x1F3F5},
	{0x1F3F7, 0x1F3FA},
	{0x1F400, 0x1F4FD},
	{0x1F4FF, 0x1F53D},
	{0x1F549, 0x1F54E},
	{0x1F550, 0x1F567},
	{0x1F56F, 0x1F570},
	{0x1F573, 0x1F57A},
	{0x1F587, 0x1F587},
	{0x1F58A, 0x1F58D},
	{0x1F590, 0x1F590},
	{0x1F595, 0x1F596},
	{0x1F5A4, 0x1F5A5},
	{0x1F5A8, 0x1F5A8},
	{0x1F5B1, 0x1F5B2},
	{0x1F5BC, 0x1F5BC},
	{0x1F5C2, 0x1F5C4},
	{0x1F5D1, 0x1F5D3},
	{0x1F5DC, 0x1F5DE},
	{0x1F5E1, 0x1F5E1},
	{0x1F5E3, 0x1F5E3},
	{0x1F5E8, 0x1F5E8},
	{0x1F5EF, 0x1F5EF},
	{0x1F5F3, 0x1F5F3},
	{0x1F5FA, 0x1F64F},
	{0x1F680, 0x1F6C5},
	{0x1F6CB, 0x1F6D2},
	{0x1F6D5, 0x1F6E5},
	{0x1F6E9, 0x1F6E9},
	{0x1F6EB, 0x1F6F0},
	{0x1F6F3, 0x1F6FF},
	{0x1F7DA, 0x1F7FF},
	{0x1F80C, 0x1F80F},
	{0x1F848, 0x1F84F},
	{0x1F85A, 0x1F85F},
	{0x1F888, 0x1F88F},
	{0x1F8AE, 0x1F8AF},
	{0x1F8BC, 0x1F8BF},
	{0x1F8C2, 0x1F8CF},
	{0x1F8D9, 0x1F8FF},
	{0x1F90C, 0x1F93A},
	{0x1F93C, 0x1F945},
	{0x1F947, 0x1F9FF},
	{0x1FA58, 0x1FA5F},
	{0x1FA6E, 0x1FAFF},
	{0x1FC00, 0x1FFFD},
}
