// Code generated by cmd/gen-indic-table. DO NOT EDIT.
// Source: IndicSyllabicCategory.txt, IndicPositionalCategory.txt, Blocks.txt
// from https://unicode.org/Public/UCD/latest/ucd/
//
// HarfBuzz equivalent: hb-ot-shaper-indic-table.cc

package ot

// Indic character classification table.
//
// This table maps Unicode codepoints to their Indic category and position.

// GetIndicCategories returns the category and position for a Unicode codepoint.
// HarfBuzz equivalent: hb_indic_get_categories()
func GetIndicCategories(u Codepoint) (IndicCategory, IndicPosition) {
	combined := getIndicCategoriesRaw(u)
	return getIndicCategory(combined), getIndicPosition(combined)
}

// Helper function for table building
func indicCombine(cat IndicCategory, pos IndicPosition) uint16 {
	return uint16(cat) | (uint16(pos) << 8)
}

// Shorthand constants for Indic table building
const (
	i_X   uint16 = uint16(ICatX) | (uint16(IPosEnd) << 8)
	i_C   uint16 = uint16(ICatC) | (uint16(IPosBaseC) << 8)
	i_V   uint16 = uint16(ICatV) | (uint16(IPosBaseC) << 8)
	i_N   uint16 = uint16(ICatN) | (uint16(IPosEnd) << 8)
	i_H   uint16 = uint16(ICatH) | (uint16(IPosBelowC) << 8)
	i_HT  uint16 = uint16(ICatH) | (uint16(IPosAboveC) << 8)
	i_M   uint16 = uint16(ICatM) | (uint16(IPosAfterSub) << 8)
	i_MA  uint16 = uint16(ICatM) | (uint16(IPosAfterMain) << 8)
	i_ML  uint16 = uint16(ICatM) | (uint16(IPosPreM) << 8)
	i_MP  uint16 = uint16(ICatM) | (uint16(IPosAfterPost) << 8)
	i_MB  uint16 = uint16(ICatM) | (uint16(IPosBeforeSub) << 8)
	i_SM  uint16 = uint16(ICatSM) | (uint16(IPosSMVD) << 8)
	i_SP  uint16 = uint16(ICatSMPst) | (uint16(IPosSMVD) << 8)
	i_A   uint16 = uint16(ICatA) | (uint16(IPosSMVD) << 8)
	i_S   uint16 = uint16(ICatSymbol) | (uint16(IPosSMVD) << 8)
	i_GB  uint16 = uint16(ICatPLACEHOLDER) | (uint16(IPosBaseC) << 8)
	i_DC  uint16 = uint16(ICatDOTTEDCIRCLE) | (uint16(IPosBaseC) << 8)
	i_R   uint16 = uint16(ICatRa) | (uint16(IPosBaseC) << 8)
	i_Rf  uint16 = uint16(ICatRepha) | (uint16(IPosEnd) << 8)
	i_CS  uint16 = uint16(ICatCS) | (uint16(IPosBaseC) << 8)
	i_CM  uint16 = uint16(ICatCM) | (uint16(IPosBaseC) << 8)
	i_MP2 uint16 = uint16(ICatMPst) | (uint16(IPosAfterPost) << 8)
)

// getIndicCategoriesRaw returns combined category/position for a codepoint.
func getIndicCategoriesRaw(u Codepoint) uint16 {
	// Special cases
	if u == 0x00A0 {
		return i_GB // NO-BREAK SPACE as placeholder
	}
	if u == 0x200C {
		return indicCombine(ICatZWNJ, IPosEnd)
	}
	if u == 0x200D {
		return indicCombine(ICatZWJ, IPosEnd)
	}
	if u == 0x25CC {
		return i_DC
	}

	// Indic scripts
	if u >= 0x0900 && u <= 0x0D7F {
		return indicTableIndic[u-0x0900]
	}

	// Myanmar
	if u >= 0x1000 && u <= 0x109F {
		return indicTableMyanmar[u-0x1000]
	}

	// Khmer
	if u >= 0x1780 && u <= 0x17EF {
		return indicTableKhmer[u-0x1780]
	}

	// Vedic Extensions
	if u >= 0x1CD0 && u <= 0x1CFF {
		return indicTableVedic[u-0x1CD0]
	}

	// Devanagari Extended
	if u >= 0xA8E0 && u <= 0xA8FF {
		return indicTableDevanagariExt[u-0xA8E0]
	}

	// Grantha (1)
	if u >= 0x11300 && u <= 0x11307 {
		return indicTableGrantha1[u-0x11300]
	}

	// Grantha (2)
	if u >= 0x11338 && u <= 0x1133F {
		return indicTableGrantha2[u-0x11338]
	}

	return i_X
}

// indicTableIndic table (0x0900-0x0D7F)
var indicTableIndic = [1152]uint16{

	// Devanagari 0x0900-...
	i_SM, i_SM, i_SM, i_SM, i_V, i_V, i_V, i_V,
	i_V, i_V, i_V, i_V, i_V, i_V, i_V, i_V,
	i_V, i_V, i_V, i_V, i_V, i_C, i_C, i_C,
	i_C, i_C, i_C, i_C, i_C, i_C, i_C, i_C,
	i_C, i_C, i_C, i_C, i_C, i_C, i_C, i_C,
	i_C, i_C, i_C, i_C, i_C, i_C, i_C, i_C,
	i_R, i_C, i_C, i_C, i_C, i_C, i_C, i_C,
	i_C, i_C, i_M, i_M, i_N, i_S, i_M, i_ML,
	i_M, i_M, i_M, i_M, i_M, i_M, i_M, i_M,
	i_M, i_M, i_M, i_M, i_M, i_H, i_ML, i_M,
	i_X, i_A, i_A, i_SM, i_SM, i_M, i_M, i_M,
	i_C, i_C, i_C, i_C, i_C, i_C, i_C, i_C,
	i_V, i_V, i_M, i_M, i_X, i_X, i_GB, i_GB,
	i_GB, i_GB, i_GB, i_GB, i_GB, i_GB, i_GB, i_GB,
	i_X, i_X, i_V, i_V, i_V, i_V, i_V, i_V,
	i_C, i_C, i_C, i_C, i_C, i_C, i_C, i_C,

	// Bengali 0x0980-...
	i_GB, i_SM, i_SM, i_SM, i_X, i_V, i_V, i_V,
	i_V, i_V, i_V, i_V, i_V, i_X, i_X, i_V,
	i_V, i_X, i_X, i_V, i_V, i_C, i_C, i_C,
	i_C, i_C, i_C, i_C, i_C, i_C, i_C, i_C,
	i_C, i_C, i_C, i_C, i_C, i_C, i_C, i_C,
	i_C, i_X, i_C, i_C, i_C, i_C, i_C, i_C,
	i_R, i_X, i_C, i_X, i_X, i_X, i_C, i_C,
	i_C, i_C, i_X, i_X, i_N, i_S, i_MP, i_ML,
	i_MP, i_M, i_M, i_M, i_M, i_X, i_X, i_ML,
	i_ML, i_X, i_X, i_MP, i_MP, i_H, i_C, i_X,
	i_X, i_X, i_X, i_X, i_X, i_X, i_X, i_MP,
	i_X, i_X, i_X, i_X, i_C, i_C, i_X, i_C,
	i_V, i_V, i_M, i_M, i_X, i_X, i_GB, i_GB,
	i_GB, i_GB, i_GB, i_GB, i_GB, i_GB, i_GB, i_GB,
	i_R, i_C, i_X, i_X, i_X, i_X, i_X, i_X,
	i_X, i_X, i_X, i_X, i_GB, i_X, i_SM, i_X,

	// Gurmukhi 0x0A00-...
	i_X, i_SM, i_SM, i_SM, i_X, i_V, i_V, i_V,
	i_V, i_V, i_V, i_X, i_X, i_X, i_X, i_V,
	i_V, i_X, i_X, i_V, i_V, i_C, i_C, i_C,
	i_C, i_C, i_C, i_C, i_C, i_C, i_C, i_C,
	i_C, i_C, i_C, i_C, i_C, i_C, i_C, i_C,
	i_C, i_X, i_C, i_C, i_C, i_C, i_C, i_C,
	i_R, i_X, i_C, i_C, i_X, i_C, i_C, i_X,
	i_C, i_C, i_X, i_X, i_N, i_X, i_MP, i_ML,
	i_MP2, i_MP, i_MP, i_X, i_X, i_X, i_X, i_MP,
	i_MP, i_X, i_X, i_MP, i_MP, i_H, i_X, i_X,
	i_X, i_MP, i_X, i_X, i_X, i_X, i_X, i_X,
	i_X, i_C, i_C, i_C, i_C, i_X, i_C, i_X,
	i_X, i_X, i_X, i_X, i_X, i_X, i_GB, i_GB,
	i_GB, i_GB, i_GB, i_GB, i_GB, i_GB, i_GB, i_GB,
	i_SM, i_SM, i_C, i_C, i_X, i_CM, i_X, i_X,
	i_X, i_X, i_X, i_X, i_X, i_X, i_X, i_X,

	// Gujarati 0x0A80-...
	i_X, i_SM, i_SM, i_SM, i_X, i_V, i_V, i_V,
	i_V, i_V, i_V, i_V, i_V, i_V, i_X, i_V,
	i_V, i_V, i_X, i_V, i_V, i_C, i_C, i_C,
	i_C, i_C, i_C, i_C, i_C, i_C, i_C, i_C,
	i_C, i_C, i_C, i_C, i_C, i_C, i_C, i_C,
	i_C, i_X, i_C, i_C, i_C, i_C, i_C, i_C,
	i_R, i_X, i_C, i_C, i_X, i_C, i_C, i_C,
	i_C, i_C, i_X, i_X, i_N, i_S, i_MP, i_ML,
	i_MP, i_MP, i_MP, i_MP, i_MP, i_M, i_X, i_M,
	i_M, i_MP, i_X, i_MP, i_MP, i_H, i_X, i_X,
	i_X, i_X, i_X, i_X, i_X, i_X, i_X, i_X,
	i_X, i_X, i_X, i_X, i_X, i_X, i_X, i_X,
	i_V, i_V, i_MP, i_MP, i_X, i_X, i_GB, i_GB,
	i_GB, i_GB, i_GB, i_GB, i_GB, i_GB, i_GB, i_GB,
	i_X, i_X, i_X, i_X, i_X, i_X, i_X, i_X,
	i_X, i_C, i_A, i_N, i_A, i_N, i_N, i_N,

	// Oriya 0x0B00-...
	i_X, i_SM, i_SM, i_SM, i_X, i_V, i_V, i_V,
	i_V, i_V, i_V, i_V, i_V, i_X, i_X, i_V,
	i_V, i_X, i_X, i_V, i_V, i_C, i_C, i_C,
	i_C, i_C, i_C, i_C, i_C, i_C, i_C, i_C,
	i_C, i_C, i_C, i_C, i_C, i_C, i_C, i_C,
	i_C, i_X, i_C, i_C, i_C, i_C, i_C, i_C,
	i_R, i_X, i_C, i_C, i_X, i_C, i_C, i_C,
	i_C, i_C, i_X, i_X, i_N, i_S, i_MP, i_MA,
	i_MP, i_M, i_M, i_M, i_M, i_X, i_X, i_ML,
	i_MA, i_X, i_X, i_MP, i_MP, i_H, i_X, i_X,
	i_X, i_X, i_X, i_X, i_X, i_N, i_MA, i_MP,
	i_X, i_X, i_X, i_X, i_C, i_C, i_X, i_C,
	i_V, i_V, i_M, i_M, i_X, i_X, i_GB, i_GB,
	i_GB, i_GB, i_GB, i_GB, i_GB, i_GB, i_GB, i_GB,
	i_X, i_C, i_X, i_X, i_X, i_X, i_X, i_X,
	i_X, i_X, i_X, i_X, i_X, i_X, i_X, i_X,

	// Tamil 0x0B80-...
	i_X, i_X, i_SM, i_X, i_X, i_V, i_V, i_V,
	i_V, i_V, i_V, i_X, i_X, i_X, i_V, i_V,
	i_V, i_X, i_V, i_V, i_V, i_C, i_X, i_X,
	i_X, i_C, i_C, i_X, i_C, i_X, i_C, i_C,
	i_X, i_X, i_X, i_C, i_C, i_X, i_X, i_X,
	i_C, i_C, i_C, i_X, i_X, i_X, i_C, i_C,
	i_R, i_C, i_C, i_C, i_C, i_C, i_C, i_C,
	i_C, i_C, i_X, i_X, i_X, i_X, i_MP, i_MP,
	i_M, i_MP, i_MP, i_X, i_X, i_X, i_ML, i_ML,
	i_ML, i_X, i_MP, i_MP, i_MP, i_HT, i_X, i_X,
	i_X, i_X, i_X, i_X, i_X, i_X, i_X, i_MP,
	i_X, i_X, i_X, i_X, i_X, i_X, i_X, i_X,
	i_X, i_X, i_X, i_X, i_X, i_X, i_GB, i_GB,
	i_GB, i_GB, i_GB, i_GB, i_GB, i_GB, i_GB, i_GB,
	i_X, i_X, i_X, i_X, i_X, i_X, i_X, i_X,
	i_X, i_X, i_X, i_X, i_X, i_X, i_X, i_X,

	// Telugu 0x0C00-...
	i_SM, i_SM, i_SM, i_SM, i_SM, i_V, i_V, i_V,
	i_V, i_V, i_V, i_V, i_V, i_X, i_V, i_V,
	i_V, i_X, i_V, i_V, i_V, i_C, i_C, i_C,
	i_C, i_C, i_C, i_C, i_C, i_C, i_C, i_C,
	i_C, i_C, i_C, i_C, i_C, i_C, i_C, i_C,
	i_C, i_X, i_C, i_C, i_C, i_C, i_C, i_C,
	i_R, i_C, i_C, i_C, i_C, i_C, i_C, i_C,
	i_C, i_C, i_X, i_X, i_N, i_S, i_MB, i_MB,
	i_MB, i_MB, i_MB, i_M, i_M, i_X, i_MB, i_MB,
	i_MB, i_X, i_MB, i_MB, i_MB, i_HT, i_X, i_X,
	i_X, i_X, i_X, i_X, i_X, i_MB, i_MB, i_X,
	i_C, i_C, i_C, i_X, i_X, i_C, i_X, i_X,
	i_V, i_V, i_MB, i_MB, i_X, i_X, i_GB, i_GB,
	i_GB, i_GB, i_GB, i_GB, i_GB, i_GB, i_GB, i_GB,
	i_X, i_X, i_X, i_X, i_X, i_X, i_X, i_X,
	i_X, i_X, i_X, i_X, i_X, i_X, i_X, i_X,

	// Kannada 0x0C80-...
	i_GB, i_SM, i_SM, i_SM, i_X, i_V, i_V, i_V,
	i_V, i_V, i_V, i_V, i_V, i_X, i_V, i_V,
	i_V, i_X, i_V, i_V, i_V, i_C, i_C, i_C,
	i_C, i_C, i_C, i_C, i_C, i_C, i_C, i_C,
	i_C, i_C, i_C, i_C, i_C, i_C, i_C, i_C,
	i_C, i_X, i_C, i_C, i_C, i_C, i_C, i_C,
	i_R, i_C, i_C, i_C, i_X, i_C, i_C, i_C,
	i_C, i_C, i_X, i_X, i_N, i_S, i_MB, i_MB,
	i_MB, i_MB, i_MB, i_M, i_M, i_X, i_MB, i_M,
	i_M, i_X, i_M, i_M, i_MB, i_HT, i_X, i_X,
	i_X, i_X, i_X, i_X, i_X, i_M, i_M, i_X,
	i_X, i_X, i_X, i_X, i_X, i_C, i_C, i_X,
	i_V, i_V, i_MB, i_MB, i_X, i_X, i_GB, i_GB,
	i_GB, i_GB, i_GB, i_GB, i_GB, i_GB, i_GB, i_GB,
	i_X, i_CS, i_CS, i_SM, i_X, i_X, i_X, i_X,
	i_X, i_X, i_X, i_X, i_X, i_X, i_X, i_X,

	// Malayalam 0x0D00-...
	i_SM, i_SM, i_SM, i_SM, i_GB, i_V, i_V, i_V,
	i_V, i_V, i_V, i_V, i_V, i_X, i_V, i_V,
	i_V, i_X, i_V, i_V, i_V, i_C, i_C, i_C,
	i_C, i_C, i_C, i_C, i_C, i_C, i_C, i_C,
	i_C, i_C, i_C, i_C, i_C, i_C, i_C, i_C,
	i_C, i_C, i_C, i_C, i_C, i_C, i_C, i_C,
	i_R, i_C, i_C, i_C, i_C, i_C, i_C, i_C,
	i_C, i_C, i_C, i_M, i_M, i_S, i_MP, i_MP,
	i_MP, i_MP, i_MP, i_MP, i_MP, i_X, i_ML, i_ML,
	i_ML, i_X, i_MP, i_MP, i_MP, i_HT, i_Rf, i_X,
	i_X, i_X, i_X, i_X, i_C, i_C, i_C, i_MP,
	i_X, i_X, i_X, i_X, i_X, i_X, i_X, i_V,
	i_V, i_V, i_MP, i_MP, i_X, i_X, i_GB, i_GB,
	i_GB, i_GB, i_GB, i_GB, i_GB, i_GB, i_GB, i_GB,
	i_X, i_X, i_X, i_X, i_X, i_X, i_X, i_X,
	i_X, i_X, i_C, i_C, i_C, i_C, i_C, i_C,
}

// indicTableMyanmar table (0x1000-0x109F)
var indicTableMyanmar = [160]uint16{

	// Myanmar 0x1000-...
	i_C, i_C, i_C, i_C, i_R, i_C, i_C, i_C,
	i_C, i_C, i_C, i_C, i_C, i_C, i_C, i_C,
	i_C, i_C, i_C, i_C, i_C, i_C, i_C, i_C,
	i_C, i_C, i_C, i_R, i_C, i_C, i_C, i_C,
	i_C, i_V, i_V, i_V, i_V, i_V, i_V, i_V,
	i_V, i_V, i_V, i_M, i_M, i_M, i_M, i_M,
	i_M, i_ML, i_A, i_M, i_M, i_M, i_A, i_N,
	i_SM, i_H, i_X, i_X, i_X, i_X, i_X, i_C,
	i_GB, i_GB, i_GB, i_GB, i_GB, i_GB, i_GB, i_GB,
	i_GB, i_GB, i_GB, i_GB, i_X, i_X, i_C, i_X,
	i_C, i_C, i_V, i_V, i_V, i_V, i_M, i_M,
	i_M, i_M, i_R, i_C, i_C, i_C, i_X, i_X,
	i_X, i_C, i_M, i_X, i_X, i_C, i_C, i_M,
	i_M, i_X, i_X, i_X, i_X, i_X, i_C, i_C,
	i_C, i_M, i_M, i_M, i_M, i_C, i_C, i_C,
	i_C, i_C, i_C, i_C, i_C, i_C, i_C, i_C,
	i_C, i_C, i_X, i_M, i_ML, i_M, i_M, i_SM,
	i_SM, i_SM, i_SM, i_SM, i_SM, i_SM, i_C, i_SM,
	i_GB, i_GB, i_GB, i_GB, i_GB, i_GB, i_GB, i_GB,
	i_GB, i_GB, i_SM, i_SM, i_SM, i_M, i_X, i_X,
}

// indicTableKhmer table (0x1780-0x17EF)
var indicTableKhmer = [112]uint16{

	// Khmer 0x1780-...
	i_C, i_C, i_C, i_C, i_C, i_C, i_C, i_C,
	i_C, i_C, i_C, i_C, i_C, i_C, i_C, i_C,
	i_C, i_C, i_C, i_C, i_C, i_C, i_C, i_C,
	i_C, i_C, i_R, i_C, i_C, i_C, i_C, i_C,
	i_C, i_C, i_C, i_V, i_V, i_V, i_V, i_V,
	i_V, i_V, i_V, i_V, i_V, i_V, i_V, i_V,
	i_V, i_V, i_V, i_V, i_X, i_X, i_M, i_M,
	i_M, i_M, i_M, i_M, i_M, i_M, i_M, i_M,
	i_M, i_ML, i_ML, i_ML, i_M, i_M, i_X, i_X,
	i_X, i_X, i_X, i_X, i_X, i_X, i_X, i_X,
	i_X, i_X, i_H, i_X, i_X, i_X, i_X, i_X,
	i_X, i_GB, i_X, i_X, i_S, i_X, i_X, i_X,
	i_GB, i_GB, i_GB, i_GB, i_GB, i_GB, i_GB, i_GB,
	i_GB, i_GB, i_X, i_X, i_X, i_X, i_X, i_X,
}

// indicTableVedic table (0x1CD0-0x1CFF)
var indicTableVedic = [48]uint16{

	// Vedic Extensions 0x1CD0-...
	i_A, i_A, i_A, i_X, i_A, i_A, i_A, i_A,
	i_A, i_A, i_A, i_A, i_A, i_A, i_A, i_A,
	i_A, i_A, i_A, i_A, i_A, i_A, i_A, i_A,
	i_A, i_S, i_S, i_S, i_S, i_A, i_S, i_S,
	i_S, i_S, i_C, i_C, i_A, i_C, i_C, i_A,
	i_A, i_A, i_GB, i_X, i_X, i_X, i_X, i_X,
}

// indicTableDevanagariExt table (0xA8E0-0xA8FF)
var indicTableDevanagariExt = [32]uint16{

	// Devanagari Extended 0xA8E0-...
	i_A, i_A, i_A, i_A, i_A, i_A, i_A, i_A,
	i_A, i_A, i_A, i_A, i_A, i_A, i_A, i_A,
	i_A, i_A, i_S, i_S, i_S, i_S, i_S, i_S,
	i_X, i_X, i_X, i_X, i_X, i_X, i_V, i_M,
}

// indicTableGrantha1 table (0x11300-0x11307)
var indicTableGrantha1 = [8]uint16{

	// Grantha 0x11300-...
	i_X, i_SM, i_SM, i_SM, i_X, i_X, i_X, i_X,
}

// indicTableGrantha2 table (0x11338-0x1133F)
var indicTableGrantha2 = [8]uint16{

	// Grantha 0x11338-...
	i_X, i_X, i_X, i_N, i_N, i_X, i_X, i_X,
}
