// Code generated by cmd/gen-use-table. DO NOT EDIT.
// Source: IndicSyllabicCategory.txt, IndicPositionalCategory.txt, Scripts.txt, Blocks.txt
// from https://unicode.org/Public/UCD/latest/ucd/
//
// HarfBuzz equivalent: hb-ot-shaper-use-table.hh

package ot

// USE table - maps codepoints to USE categories
//
// This table is generated from Unicode data files.
// Scripts with their own shapers (Arabic, Thai, etc.) are excluded.

// getUSECategory returns the USE category for a codepoint.
// HarfBuzz equivalent: hb_use_get_category() in hb-ot-shaper-use-table.hh
func getUSECategory(cp Codepoint) USECategory {
	// Special characters
	switch cp {
	case 0x200C: // ZWNJ
		return USE_ZWNJ
	case 0x200D: // ZWJ
		return USE_WJ
	case 0x034F: // COMBINING GRAPHEME JOINER
		return USE_CGJ
	case 0x2060: // WORD JOINER
		return USE_WJ
	case 0x25CC: // DOTTED CIRCLE - Base in USE (HarfBuzz: hb_use_get_category returns B)
		return USE_B
	}
	if cp >= 0x002D && cp <= 0x0039 {
		return useTable002D[cp-0x002D]
	}

	if cp >= 0x00A0 && cp <= 0x00D7 {
		return useTable00A0[cp-0x00A0]
	}

	if cp >= 0x0900 && cp <= 0x097F {
		return useTable0900[cp-0x0900]
	}

	if cp >= 0x0980 && cp <= 0x09FE {
		return useTable0980[cp-0x0980]
	}

	if cp >= 0x0A01 && cp <= 0x0A75 {
		return useTable0A01[cp-0x0A01]
	}

	if cp >= 0x0A81 && cp <= 0x0AFF {
		return useTable0A81[cp-0x0A81]
	}

	if cp >= 0x0B01 && cp <= 0x0B71 {
		return useTable0B01[cp-0x0B01]
	}

	if cp >= 0x0B82 && cp <= 0x0BEF {
		return useTable0B82[cp-0x0B82]
	}

	if cp >= 0x0C00 && cp <= 0x0C6F {
		return useTable0C00[cp-0x0C00]
	}

	if cp >= 0x0C80 && cp <= 0x0CF3 {
		return useTable0C80[cp-0x0C80]
	}

	if cp >= 0x0D00 && cp <= 0x0D7F {
		return useTable0D00[cp-0x0D00]
	}

	if cp >= 0x0D81 && cp <= 0x0DF3 {
		return useTable0D81[cp-0x0D81]
	}

	if cp >= 0x0F20 && cp <= 0x0FC6 {
		return useTable0F20[cp-0x0F20]
	}

	if cp >= 0x1000 && cp <= 0x109D {
		return useTable1000[cp-0x1000]
	}

	if cp >= 0x1700 && cp <= 0x171F {
		return useTable1700[cp-0x1700]
	}

	if cp >= 0x1720 && cp <= 0x1734 {
		return useTable1720[cp-0x1720]
	}

	if cp >= 0x1740 && cp <= 0x1753 {
		return useTable1740[cp-0x1740]
	}

	if cp >= 0x1760 && cp <= 0x1773 {
		return useTable1760[cp-0x1760]
	}

	if cp >= 0x1780 && cp <= 0x17E9 {
		return useTable1780[cp-0x1780]
	}

	if cp >= 0x1900 && cp <= 0x194F {
		return useTable1900[cp-0x1900]
	}

	if cp >= 0x1950 && cp <= 0x1974 {
		return useTable1950[cp-0x1950]
	}

	if cp >= 0x1980 && cp <= 0x19DA {
		return useTable1980[cp-0x1980]
	}

	if cp >= 0x1A00 && cp <= 0x1A1B {
		return useTable1A00[cp-0x1A00]
	}

	if cp >= 0x1A20 && cp <= 0x1A99 {
		return useTable1A20[cp-0x1A20]
	}

	if cp >= 0x1B00 && cp <= 0x1B59 {
		return useTable1B00[cp-0x1B00]
	}

	if cp >= 0x1B80 && cp <= 0x1BBF {
		return useTable1B80[cp-0x1B80]
	}

	if cp >= 0x1BC0 && cp <= 0x1BF3 {
		return useTable1BC0[cp-0x1BC0]
	}

	if cp >= 0x1C00 && cp <= 0x1C4F {
		return useTable1C00[cp-0x1C00]
	}

	if cp >= 0x1CD0 && cp <= 0x1CFA {
		return useTable1CD0[cp-0x1CD0]
	}

	if cp >= 0x200C && cp <= 0x2014 {
		return useTable200C[cp-0x200C]
	}

	if cp >= 0x2074 && cp <= 0x2084 {
		return useTable2074[cp-0x2074]
	}

	if cp >= 0xA800 && cp <= 0xA82C {
		return useTableA800[cp-0xA800]
	}

	if cp >= 0xA840 && cp <= 0xA873 {
		return useTableA840[cp-0xA840]
	}

	if cp >= 0xA880 && cp <= 0xA8D9 {
		return useTableA880[cp-0xA880]
	}

	if cp >= 0xA8E0 && cp <= 0xA8FF {
		return useTableA8E0[cp-0xA8E0]
	}

	if cp >= 0xA900 && cp <= 0xA92D {
		return useTableA900[cp-0xA900]
	}

	if cp >= 0xA930 && cp <= 0xA953 {
		return useTableA930[cp-0xA930]
	}

	if cp >= 0xA980 && cp <= 0xA9D9 {
		return useTableA980[cp-0xA980]
	}

	if cp >= 0xA9E0 && cp <= 0xA9FE {
		return useTableA9E0[cp-0xA9E0]
	}

	if cp >= 0xAA00 && cp <= 0xAA59 {
		return useTableAA00[cp-0xAA00]
	}

	if cp >= 0xAA60 && cp <= 0xAA7F {
		return useTableAA60[cp-0xAA60]
	}

	if cp >= 0xAA80 && cp <= 0xAAC2 {
		return useTableAA80[cp-0xAA80]
	}

	if cp >= 0xAAE0 && cp <= 0xAAF6 {
		return useTableAAE0[cp-0xAAE0]
	}

	if cp >= 0xABC0 && cp <= 0xABF9 {
		return useTableABC0[cp-0xABC0]
	}

	if cp >= 0x10A00 && cp <= 0x10A48 {
		return useTable10A00[cp-0x10A00]
	}

	if cp >= 0x11000 && cp <= 0x1107F {
		return useTable11000[cp-0x11000]
	}

	if cp >= 0x11080 && cp <= 0x110C2 {
		return useTable11080[cp-0x11080]
	}

	if cp >= 0x11100 && cp <= 0x11147 {
		return useTable11100[cp-0x11100]
	}

	if cp >= 0x11150 && cp <= 0x11173 {
		return useTable11150[cp-0x11150]
	}

	if cp >= 0x11180 && cp <= 0x111D9 {
		return useTable11180[cp-0x11180]
	}

	if cp >= 0x111E1 && cp <= 0x111F4 {
		return useTable111E1[cp-0x111E1]
	}

	if cp >= 0x11200 && cp <= 0x11241 {
		return useTable11200[cp-0x11200]
	}

	if cp >= 0x11280 && cp <= 0x112A8 {
		return useTable11280[cp-0x11280]
	}

	if cp >= 0x112B0 && cp <= 0x112F9 {
		return useTable112B0[cp-0x112B0]
	}

	if cp >= 0x11300 && cp <= 0x11374 {
		return useTable11300[cp-0x11300]
	}

	if cp >= 0x11380 && cp <= 0x113E2 {
		return useTable11380[cp-0x11380]
	}

	if cp >= 0x11400 && cp <= 0x11461 {
		return useTable11400[cp-0x11400]
	}

	if cp >= 0x11481 && cp <= 0x114D9 {
		return useTable11481[cp-0x11481]
	}

	if cp >= 0x11580 && cp <= 0x115DD {
		return useTable11580[cp-0x11580]
	}

	if cp >= 0x11600 && cp <= 0x11659 {
		return useTable11600[cp-0x11600]
	}

	if cp >= 0x11680 && cp <= 0x116C9 {
		return useTable11680[cp-0x11680]
	}

	if cp >= 0x116D0 && cp <= 0x116E3 {
		return useTable116D0[cp-0x116D0]
	}

	if cp >= 0x11700 && cp <= 0x11746 {
		return useTable11700[cp-0x11700]
	}

	if cp >= 0x11800 && cp <= 0x1183A {
		return useTable11800[cp-0x11800]
	}

	if cp >= 0x11900 && cp <= 0x11959 {
		return useTable11900[cp-0x11900]
	}

	if cp >= 0x119A0 && cp <= 0x119E4 {
		return useTable119A0[cp-0x119A0]
	}

	if cp >= 0x11A00 && cp <= 0x11A47 {
		return useTable11A00[cp-0x11A00]
	}

	if cp >= 0x11A50 && cp <= 0x11A9D {
		return useTable11A50[cp-0x11A50]
	}

	if cp >= 0x11C00 && cp <= 0x11C6C {
		return useTable11C00[cp-0x11C00]
	}

	if cp >= 0x11C72 && cp <= 0x11CB6 {
		return useTable11C72[cp-0x11C72]
	}

	if cp >= 0x11D00 && cp <= 0x11D59 {
		return useTable11D00[cp-0x11D00]
	}

	if cp >= 0x11D60 && cp <= 0x11DA9 {
		return useTable11D60[cp-0x11D60]
	}

	if cp >= 0x11EE0 && cp <= 0x11EF6 {
		return useTable11EE0[cp-0x11EE0]
	}

	if cp >= 0x11F00 && cp <= 0x11F5A {
		return useTable11F00[cp-0x11F00]
	}

	if cp >= 0x16100 && cp <= 0x16139 {
		return useTable16100[cp-0x16100]
	}

	if cp >= 0x16D40 && cp <= 0x16D79 {
		return useTable16D40[cp-0x16D40]
	}

	return USE_O
}

// Basic Latin (U+002D-U+0039)
var useTable002D = [13]USECategory{
	USE_GB, USE_O, USE_O, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N, USE_N, USE_N, USE_N,
}

// Latin-1 Supplement (U+00A0-U+00D7)
var useTable00A0 = [56]USECategory{
	USE_GB, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_O, USE_O, USE_FM, USE_FM, USE_O, USE_O, USE_O, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_GB,
}

// Devanagari (U+0900-U+097F)
var useTable0900 = [128]USECategory{
	USE_VMAbv, USE_VMAbv, USE_VMAbv, USE_VMPst, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_VAbv, USE_VPst, USE_CMBlw, USE_O, USE_VPst, USE_VPre,
	USE_VPst, USE_VBlw, USE_VBlw, USE_VBlw, USE_VBlw, USE_VAbv, USE_VAbv, USE_VAbv,
	USE_VAbv, USE_VPst, USE_VPst, USE_VPst, USE_VPst, USE_H, USE_VPre, USE_VPst,
	USE_O, USE_VMAbv, USE_VMBlw, USE_O, USE_O, USE_VAbv, USE_VBlw, USE_VBlw,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_VBlw, USE_VBlw, USE_O, USE_O, USE_N, USE_N,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_O, USE_O, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
}

// Bengali (U+0980-U+09FE)
var useTable0980 = [127]USECategory{
	USE_GB, USE_VMAbv, USE_VMPst, USE_VMPst, USE_O, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_O, USE_O, USE_B,
	USE_B, USE_O, USE_O, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_O, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_O, USE_B, USE_O, USE_O, USE_O, USE_B, USE_B,
	USE_B, USE_B, USE_O, USE_O, USE_CMBlw, USE_O, USE_VPst, USE_VPre,
	USE_VPst, USE_VBlw, USE_VBlw, USE_VBlw, USE_VBlw, USE_O, USE_O, USE_VPre,
	USE_VPre, USE_O, USE_O, USE_VPst, USE_VPst, USE_H, USE_O, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_VPst,
	USE_O, USE_O, USE_O, USE_O, USE_B, USE_B, USE_O, USE_B,
	USE_B, USE_B, USE_VBlw, USE_VBlw, USE_O, USE_O, USE_N, USE_N,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_B, USE_B, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_VM, USE_O, USE_FMAbv,
}

// Gurmukhi (U+0A01-U+0A75)
var useTable0A01 = [117]USECategory{
	USE_VMAbv, USE_VMAbv, USE_VMPst, USE_O, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_O, USE_O, USE_O, USE_O, USE_B, USE_B,
	USE_O, USE_O, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_O, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_O, USE_B, USE_B, USE_O, USE_B, USE_B, USE_O, USE_B,
	USE_B, USE_O, USE_O, USE_CMBlw, USE_O, USE_VPst, USE_VPre, USE_VPst,
	USE_VBlw, USE_VBlw, USE_O, USE_O, USE_O, USE_O, USE_VAbv, USE_VAbv,
	USE_O, USE_O, USE_VAbv, USE_VAbv, USE_H, USE_O, USE_O, USE_O,
	USE_VMBlw, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_B, USE_B, USE_B, USE_B, USE_O, USE_B, USE_O, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_N, USE_N, USE_N,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_VMAbv,
	USE_CMAbv, USE_GB, USE_GB, USE_O, USE_MBlw,
}

// Gujarati (U+0A81-U+0AFF)
var useTable0A81 = [127]USECategory{
	USE_VMAbv, USE_VMAbv, USE_VMPst, USE_O, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_O, USE_B, USE_B,
	USE_B, USE_O, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_O, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_O, USE_B, USE_B, USE_O, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_O, USE_O, USE_CMBlw, USE_O, USE_VPst, USE_VPre, USE_VPst,
	USE_VBlw, USE_VBlw, USE_VBlw, USE_VBlw, USE_VAbv, USE_O, USE_VAbv, USE_VAbv,
	USE_VPst, USE_O, USE_VPst, USE_VPst, USE_H, USE_O, USE_O, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_B,
	USE_B, USE_VBlw, USE_VBlw, USE_O, USE_O, USE_N, USE_N, USE_N,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_B, USE_VMAbv, USE_CMAbv, USE_VMAbv, USE_CMAbv, USE_CMAbv, USE_CMAbv,
}

// Oriya (U+0B01-U+0B71)
var useTable0B01 = [113]USECategory{
	USE_VMAbv, USE_VMPst, USE_VMPst, USE_O, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_O, USE_O, USE_B, USE_B,
	USE_O, USE_O, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_O, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_O, USE_B, USE_B, USE_O, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_O, USE_O, USE_CMBlw, USE_O, USE_VPst, USE_VAbv, USE_VPst,
	USE_VBlw, USE_VBlw, USE_VBlw, USE_VBlw, USE_O, USE_O, USE_VPre, USE_VAbv,
	USE_O, USE_O, USE_VPst, USE_VPst, USE_H, USE_O, USE_O, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_VAbv, USE_VAbv, USE_VPst, USE_O,
	USE_O, USE_O, USE_O, USE_B, USE_B, USE_O, USE_B, USE_B,
	USE_B, USE_VBlw, USE_VBlw, USE_O, USE_O, USE_N, USE_N, USE_N,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_O,
	USE_B,
}

// Tamil (U+0B82-U+0BEF)
var useTable0B82 = [110]USECategory{
	USE_VMAbv, USE_O, USE_O, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_O, USE_O, USE_O, USE_B, USE_B, USE_B, USE_O,
	USE_B, USE_B, USE_B, USE_B, USE_O, USE_O, USE_O, USE_B,
	USE_B, USE_O, USE_B, USE_O, USE_B, USE_B, USE_O, USE_O,
	USE_O, USE_B, USE_B, USE_O, USE_O, USE_O, USE_B, USE_B,
	USE_B, USE_O, USE_O, USE_O, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_O, USE_O, USE_O, USE_O, USE_VPst, USE_VPst, USE_VAbv, USE_VPst,
	USE_VPst, USE_O, USE_O, USE_O, USE_VPre, USE_VPre, USE_VPre, USE_O,
	USE_VPst, USE_VPst, USE_VPst, USE_H, USE_O, USE_O, USE_O, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_VPst, USE_O, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
}

// Telugu (U+0C00-U+0C6F)
var useTable0C00 = [112]USECategory{
	USE_VMAbv, USE_VMPst, USE_VMPst, USE_VMPst, USE_VMAbv, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_O, USE_B, USE_B,
	USE_B, USE_O, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_O, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_O, USE_O, USE_CMBlw, USE_O, USE_VAbv, USE_VAbv,
	USE_VAbv, USE_VPst, USE_VPst, USE_VPst, USE_VPst, USE_O, USE_VAbv, USE_VAbv,
	USE_VBlw, USE_O, USE_VAbv, USE_VAbv, USE_VAbv, USE_H, USE_O, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_VAbv, USE_VBlw, USE_O,
	USE_B, USE_B, USE_B, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_B, USE_B, USE_VBlw, USE_VBlw, USE_O, USE_O, USE_N, USE_N,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
}

// Kannada (U+0C80-U+0CF3)
var useTable0C80 = [116]USECategory{
	USE_VM, USE_VMAbv, USE_VMPst, USE_VMPst, USE_O, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_O, USE_B, USE_B,
	USE_B, USE_O, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_O, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_O, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_O, USE_O, USE_CMBlw, USE_O, USE_VPst, USE_VAbv,
	USE_VPst, USE_VPst, USE_VPst, USE_VPst, USE_VPst, USE_O, USE_VAbv, USE_VPst,
	USE_VPst, USE_O, USE_VPst, USE_VPst, USE_VAbv, USE_H, USE_O, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_VPst, USE_VPst, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_B, USE_O,
	USE_B, USE_B, USE_VBlw, USE_VBlw, USE_O, USE_O, USE_N, USE_N,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_O, USE_CS, USE_CS, USE_VMPst,
}

// Malayalam (U+0D00-U+0D7F)
var useTable0D00 = [128]USECategory{
	USE_VMAbv, USE_VMAbv, USE_VMPst, USE_VMPst, USE_VM, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_O, USE_B, USE_B,
	USE_B, USE_O, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_VAbv, USE_VAbv, USE_O, USE_VPst, USE_VPst,
	USE_VPst, USE_VBlw, USE_VBlw, USE_VBlw, USE_VBlw, USE_O, USE_VPre, USE_VPre,
	USE_VPre, USE_O, USE_VPst, USE_VPst, USE_VPst, USE_H, USE_R, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_VPst,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_B,
	USE_B, USE_B, USE_VBlw, USE_VBlw, USE_O, USE_O, USE_N, USE_N,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
}

// Sinhala (U+0D81-U+0DF3)
var useTable0D81 = [115]USECategory{
	USE_VMAbv, USE_VMPst, USE_VMPst, USE_O, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_O, USE_O,
	USE_O, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_O, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_O, USE_B, USE_O, USE_O, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_O, USE_O,
	USE_O, USE_HVM, USE_O, USE_O, USE_O, USE_O, USE_VPst, USE_VPst,
	USE_VPst, USE_VAbv, USE_VAbv, USE_VBlw, USE_O, USE_VBlw, USE_O, USE_VPst,
	USE_VPre, USE_VPre, USE_VPre, USE_VPre, USE_VPre, USE_VPre, USE_VPst, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_N, USE_N, USE_N,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_O,
	USE_O, USE_VPst, USE_VPst,
}

// Tibetan (U+0F20-U+0FC6)
var useTable0F20 = [167]USECategory{
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N, USE_N, USE_N, USE_O, USE_FMBlw, USE_O, USE_FMBlw,
	USE_O, USE_CMAbv, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_O, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_O, USE_O, USE_O,
	USE_O, USE_VBlw, USE_VAbv, USE_VBlw, USE_VBlw, USE_VBlw, USE_VBlw, USE_VBlw,
	USE_VBlw, USE_VBlw, USE_VAbv, USE_VAbv, USE_VAbv, USE_VAbv, USE_VMAbv, USE_VMPst,
	USE_VAbv, USE_VBlw, USE_VMAbv, USE_VMAbv, USE_VBlw, USE_O, USE_O, USE_O,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_SUB, USE_SUB, USE_SUB,
	USE_SUB, USE_SUB, USE_SUB, USE_SUB, USE_SUB, USE_SUB, USE_SUB, USE_SUB,
	USE_O, USE_SUB, USE_SUB, USE_SUB, USE_SUB, USE_SUB, USE_SUB, USE_SUB,
	USE_SUB, USE_SUB, USE_SUB, USE_SUB, USE_SUB, USE_SUB, USE_SUB, USE_SUB,
	USE_SUB, USE_SUB, USE_SUB, USE_SUB, USE_SUB, USE_SUB, USE_SUB, USE_SUB,
	USE_SUB, USE_SUB, USE_SUB, USE_SUB, USE_SUB, USE_SUB, USE_SUB, USE_SUB,
	USE_SUB, USE_SUB, USE_SUB, USE_SUB, USE_SUB, USE_O, USE_O, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_FMBlw,
}

// Myanmar (U+1000-U+109D)
var useTable1000 = [158]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_VPst, USE_VPst, USE_VAbv, USE_VAbv, USE_VBlw,
	USE_VBlw, USE_VPre, USE_VAbv, USE_VAbv, USE_VAbv, USE_VAbv, USE_VMAbv, USE_VMBlw,
	USE_VMPst, USE_IS, USE_VAbv, USE_MPst, USE_MBlw, USE_MBlw, USE_MBlw, USE_B,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N, USE_O, USE_GB, USE_O, USE_O, USE_GB, USE_O,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_VPst, USE_VPst,
	USE_VBlw, USE_VBlw, USE_B, USE_B, USE_B, USE_B, USE_MBlw, USE_MBlw,
	USE_MBlw, USE_B, USE_VPst, USE_VMPst, USE_VMPst, USE_B, USE_B, USE_VPst,
	USE_VPst, USE_VMPst, USE_VMPst, USE_VMPst, USE_VMPst, USE_VMPst, USE_B, USE_B,
	USE_B, USE_VAbv, USE_VAbv, USE_VAbv, USE_VAbv, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_MBlw, USE_VPst, USE_VPre, USE_VAbv, USE_VAbv, USE_VMPst,
	USE_VMPst, USE_VMPst, USE_VMPst, USE_VMPst, USE_VMPst, USE_VMBlw, USE_B, USE_VMPst,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N, USE_VMPst, USE_VMPst, USE_VPst, USE_VAbv,
}

// Tagalog (U+1700-U+171F)
var useTable1700 = [32]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_VAbv, USE_VBlw, USE_VBlw, USE_VPst, USE_O, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_B,
}

// Hanunoo (U+1720-U+1734)
var useTable1720 = [21]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_VAbv, USE_VBlw, USE_VPst,
}

// Buhid (U+1740-U+1753)
var useTable1740 = [20]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_VAbv, USE_VBlw,
}

// Tagbanwa (U+1760-U+1773)
var useTable1760 = [20]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_O, USE_B, USE_B,
	USE_B, USE_O, USE_VAbv, USE_VBlw,
}

// Khmer (U+1780-U+17E9)
var useTable1780 = [106]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_O, USE_O, USE_VPst, USE_VAbv,
	USE_VAbv, USE_VAbv, USE_VAbv, USE_VBlw, USE_VBlw, USE_VBlw, USE_VAbv, USE_VPst,
	USE_VPst, USE_VPre, USE_VPre, USE_VPre, USE_VPst, USE_VPst, USE_VMAbv, USE_VMPst,
	USE_VPst, USE_VMAbv, USE_VMAbv, USE_FMAbv, USE_FAbv, USE_CMAbv, USE_FMAbv, USE_FMAbv,
	USE_FMAbv, USE_VAbv, USE_IS, USE_FMAbv, USE_O, USE_O, USE_O, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_FMAbv, USE_O, USE_O,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N,
}

// Limbu (U+1900-U+194F)
var useTable1900 = [80]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_O,
	USE_VAbv, USE_VAbv, USE_VBlw, USE_VPst, USE_VPst, USE_VPst, USE_VPst, USE_VAbv,
	USE_VAbv, USE_SUB, USE_SUB, USE_SUB, USE_O, USE_O, USE_O, USE_O,
	USE_FPst, USE_FPst, USE_VMBlw, USE_FPst, USE_FPst, USE_FPst, USE_FPst, USE_FPst,
	USE_FPst, USE_FBlw, USE_VAbv, USE_FMBlw, USE_O, USE_O, USE_O, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_N, USE_N,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
}

// Tai Le (U+1950-U+1974)
var useTable1950 = [37]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_V, USE_V, USE_V, USE_V, USE_V,
	USE_V, USE_V, USE_V, USE_V, USE_V, USE_V, USE_O, USE_O,
	USE_B, USE_B, USE_B, USE_B, USE_B,
}

// New Tai Lue (U+1980-U+19DA)
var useTable1980 = [91]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_O, USE_O, USE_O, USE_O,
	USE_VPst, USE_VPst, USE_VPst, USE_VPst, USE_VPst, USE_VPre, USE_VPre, USE_VPre,
	USE_VPst, USE_VPst, USE_VPre, USE_VPst, USE_VPst, USE_VPst, USE_VPst, USE_VPst,
	USE_VPst, USE_F, USE_F, USE_F, USE_F, USE_F, USE_F, USE_F,
	USE_VMPst, USE_VMPst, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N, USE_N,
}

// Buginese (U+1A00-U+1A1B)
var useTable1A00 = [28]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_VAbv,
	USE_VBlw, USE_VPre, USE_VPst, USE_VAbv,
}

// Tai Tham (U+1A20-U+1A99)
var useTable1A20 = [122]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_MPre, USE_MBlw, USE_SUB,
	USE_FAbv, USE_FAbv, USE_MAbv, USE_SUB, USE_SUB, USE_SUB, USE_SUB, USE_O,
	USE_Sk, USE_VPst, USE_VAbv, USE_VPst, USE_VPst, USE_VAbv, USE_VAbv, USE_VAbv,
	USE_VAbv, USE_VBlw, USE_VBlw, USE_VAbv, USE_VBlw, USE_VPst, USE_VPre, USE_VPre,
	USE_VPre, USE_VPre, USE_VPre, USE_VAbv, USE_VMAbv, USE_VMAbv, USE_VMAbv, USE_VMAbv,
	USE_VMAbv, USE_VMAbv, USE_VAbv, USE_FMAbv, USE_FMAbv, USE_O, USE_O, USE_FMBlw,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N,
}

// Balinese (U+1B00-U+1B59)
var useTable1B00 = [90]USECategory{
	USE_VMAbv, USE_VMAbv, USE_VMAbv, USE_FAbv, USE_VMPst, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_CMAbv, USE_VPst, USE_VAbv, USE_VAbv,
	USE_VBlw, USE_VBlw, USE_VBlw, USE_VPst, USE_VBlw, USE_VPst, USE_VPre, USE_VPre,
	USE_VPst, USE_VPst, USE_VAbv, USE_VPst, USE_H, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_O, USE_O, USE_O,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N,
}

// Sundanese (U+1B80-U+1BBF)
var useTable1B80 = [64]USECategory{
	USE_VMAbv, USE_FAbv, USE_VMPst, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_SUB, USE_SUB, USE_SUB, USE_VAbv, USE_VBlw, USE_VPre, USE_VPst,
	USE_VAbv, USE_VAbv, USE_VPst, USE_IS, USE_SUB, USE_SUB, USE_B, USE_B,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N, USE_O, USE_B, USE_B, USE_B, USE_F, USE_F,
}

// Batak (U+1BC0-U+1BF3)
var useTable1BC0 = [52]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_CMAbv, USE_VPst,
	USE_VAbv, USE_VAbv, USE_VPst, USE_VPst, USE_VPst, USE_VAbv, USE_VPst, USE_VAbv,
	USE_FAbv, USE_FAbv, USE_RK, USE_RK,
}

// Lepcha (U+1C00-U+1C4F)
var useTable1C00 = [80]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_SUB, USE_SUB, USE_VPst, USE_VPre,
	USE_VPre, USE_VAbv, USE_VPst, USE_VPst, USE_VBlw, USE_FAbv, USE_FAbv, USE_FAbv,
	USE_FAbv, USE_FAbv, USE_FAbv, USE_FAbv, USE_VMPre, USE_VMPre, USE_FMAbv, USE_CMBlw,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N, USE_O, USE_O, USE_O, USE_B, USE_B, USE_B,
}

// Vedic Extensions (U+1CD0-U+1CFA)
var useTable1CD0 = [43]USECategory{
	USE_VMAbv, USE_VMAbv, USE_VMAbv, USE_O, USE_VMBlw, USE_VMBlw, USE_VMBlw, USE_VMBlw,
	USE_VMBlw, USE_VMBlw, USE_VMAbv, USE_VMAbv, USE_VMBlw, USE_VMBlw, USE_VMBlw, USE_VMBlw,
	USE_VMAbv, USE_VMPst, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_VMAbv, USE_CS, USE_CS, USE_VMPst,
	USE_VM, USE_VM, USE_GB,
}

// General Punctuation (U+200C-U+2014)
var useTable200C = [9]USECategory{
	USE_ZWNJ, USE_CGJ, USE_O, USE_O, USE_GB, USE_GB, USE_GB, USE_GB,
	USE_GB,
}

// Superscripts and Subscripts (U+2074-U+2084)
var useTable2074 = [17]USECategory{
	USE_FM, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_FM, USE_FM,
	USE_FM,
}

// Syloti Nagri (U+A800-U+A82C)
var useTableA800 = [45]USECategory{
	USE_B, USE_B, USE_VAbv, USE_B, USE_B, USE_B, USE_H, USE_B,
	USE_B, USE_B, USE_B, USE_VMAbv, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_VPst, USE_VPst, USE_VBlw, USE_VAbv, USE_VPst,
	USE_O, USE_O, USE_O, USE_O, USE_VBlw,
}

// Phags-pa (U+A840-U+A873)
var useTableA840 = [52]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_V, USE_V,
	USE_V, USE_V, USE_B, USE_B, USE_B, USE_B, USE_V, USE_SUB,
	USE_SUB, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_SUB, USE_B, USE_VM,
}

// Saurashtra (U+A880-U+A8D9)
var useTableA880 = [90]USECategory{
	USE_VMPst, USE_VMPst, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_MPst, USE_VPst, USE_VPst, USE_VPst,
	USE_VPst, USE_VPst, USE_VPst, USE_VPst, USE_VPst, USE_VPst, USE_VPst, USE_VPst,
	USE_VPst, USE_VPst, USE_VPst, USE_VPst, USE_H, USE_VMAbv, USE_O, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N,
}

// Devanagari Extended (U+A8E0-U+A8FF)
var useTableA8E0 = [32]USECategory{
	USE_VMAbv, USE_VMAbv, USE_VMAbv, USE_VMAbv, USE_VMAbv, USE_VMAbv, USE_VMAbv, USE_VMAbv,
	USE_VMAbv, USE_VMAbv, USE_VMAbv, USE_VMAbv, USE_VMAbv, USE_VMAbv, USE_VMAbv, USE_VMAbv,
	USE_VMAbv, USE_VMAbv, USE_VM, USE_VM, USE_O, USE_O, USE_O, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_B, USE_VAbv,
}

// Kayah Li (U+A900-U+A92D)
var useTableA900 = [46]USECategory{
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_V, USE_V, USE_V, USE_V, USE_VAbv, USE_VAbv,
	USE_VAbv, USE_VAbv, USE_VAbv, USE_VMBlw, USE_VMBlw, USE_VMBlw,
}

// Rejang (U+A930-U+A953)
var useTableA930 = [36]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_VBlw,
	USE_VBlw, USE_VBlw, USE_VAbv, USE_VBlw, USE_VBlw, USE_VBlw, USE_VBlw, USE_FAbv,
	USE_FAbv, USE_FAbv, USE_FPst, USE_VPst,
}

// Javanese (U+A980-U+A9D9)
var useTableA980 = [90]USECategory{
	USE_VMAbv, USE_VMAbv, USE_FAbv, USE_VMPst, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_CMAbv, USE_VPst, USE_VPst, USE_VAbv, USE_VAbv,
	USE_VBlw, USE_VBlw, USE_VPre, USE_VPre, USE_VAbv, USE_MBlw, USE_MPst, USE_MBlw,
	USE_H, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N,
}

// Myanmar Extended-B (U+A9E0-U+A9FE)
var useTableA9E0 = [31]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_VAbv, USE_O, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N, USE_B, USE_B, USE_B, USE_B, USE_B,
}

// Cham (U+AA00-U+AA59)
var useTableAA00 = [90]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_VAbv, USE_VAbv, USE_VAbv, USE_VAbv, USE_VBlw, USE_VAbv, USE_VPre,
	USE_VPre, USE_VAbv, USE_VBlw, USE_MPst, USE_MPre, USE_MBlw, USE_MBlw, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_F, USE_F, USE_F, USE_FAbv, USE_F, USE_F, USE_F, USE_F,
	USE_F, USE_F, USE_F, USE_F, USE_FAbv, USE_FPst, USE_O, USE_O,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N,
}

// Myanmar Extended-A (U+AA60-U+AA7F)
var useTableAA60 = [32]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_O, USE_B, USE_B, USE_B, USE_GB, USE_GB, USE_GB, USE_O,
	USE_O, USE_O, USE_B, USE_VMPst, USE_VMAbv, USE_VMPst, USE_B, USE_B,
}

// Tai Viet (U+AA80-U+AAC2)
var useTableAA80 = [67]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_VAbv, USE_VPst, USE_VAbv, USE_VAbv, USE_VBlw, USE_VPre, USE_VPre, USE_VAbv,
	USE_VAbv, USE_VPre, USE_VPst, USE_VPre, USE_VPre, USE_VPst, USE_VAbv, USE_VMAbv,
	USE_B, USE_VMAbv, USE_B,
}

// Meetei Mayek Extensions (U+AAE0-U+AAF6)
var useTableAAE0 = [23]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_VPre, USE_VBlw, USE_VAbv, USE_VPre, USE_VPst,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_VMPst, USE_IS,
}

// Meetei Mayek (U+ABC0-U+ABF9)
var useTableABC0 = [58]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_F, USE_F, USE_F, USE_F, USE_F,
	USE_F, USE_F, USE_F, USE_VPst, USE_VPst, USE_VAbv, USE_VPst, USE_VPst,
	USE_VBlw, USE_VPst, USE_VPst, USE_O, USE_VMPst, USE_VBlw, USE_O, USE_O,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N,
}

// Kharoshthi (U+10A00-U+10A48)
var useTable10A00 = [73]USECategory{
	USE_B, USE_VBlw, USE_VBlw, USE_VBlw, USE_O, USE_VAbv, USE_VBlw, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_VBlw, USE_VBlw, USE_VMBlw, USE_VMAbv,
	USE_B, USE_B, USE_B, USE_B, USE_O, USE_B, USE_B, USE_B,
	USE_O, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_O, USE_O,
	USE_CMAbv, USE_CMBlw, USE_CMBlw, USE_O, USE_O, USE_O, USE_O, USE_IS,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N,
}

// Brahmi (U+11000-U+1107F)
var useTable11000 = [128]USECategory{
	USE_VMPst, USE_VMAbv, USE_VMPst, USE_CS, USE_CS, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_VAbv, USE_VAbv, USE_VAbv, USE_VAbv, USE_VBlw, USE_VBlw, USE_VBlw, USE_VBlw,
	USE_VBlw, USE_VBlw, USE_VAbv, USE_VAbv, USE_VAbv, USE_VAbv, USE_H, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_O, USE_O, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_VAbv, USE_B, USE_B, USE_VAbv, USE_VAbv, USE_B, USE_O, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_HN,
}

// Kaithi (U+11080-U+110C2)
var useTable11080 = [67]USECategory{
	USE_VMAbv, USE_VMAbv, USE_VMPst, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_VPst, USE_VPre, USE_VPst, USE_VBlw, USE_VBlw, USE_VAbv, USE_VAbv, USE_VPst,
	USE_VPst, USE_H, USE_CMBlw, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_O, USE_O, USE_VBlw,
}

// Chakma (U+11100-U+11147)
var useTable11100 = [72]USECategory{
	USE_VMAbv, USE_VMAbv, USE_VMAbv, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_VBlw,
	USE_VBlw, USE_VBlw, USE_VAbv, USE_VAbv, USE_VPre, USE_VBlw, USE_VAbv, USE_VAbv,
	USE_VBlw, USE_VAbv, USE_VAbv, USE_IS, USE_CMAbv, USE_O, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_O, USE_O, USE_O, USE_O, USE_B, USE_VPst, USE_VPst, USE_B,
}

// Mahajani (U+11150-U+11173)
var useTable11150 = [36]USECategory{
	USE_V, USE_V, USE_V, USE_V, USE_V, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_CMBlw,
}

// Sharada (U+11180-U+111D9)
var useTable11180 = [90]USECategory{
	USE_VMAbv, USE_VMAbv, USE_VMPst, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_VPst, USE_VPre, USE_VPst, USE_VBlw, USE_VBlw,
	USE_VBlw, USE_VBlw, USE_VBlw, USE_VBlw, USE_VAbv, USE_VAbv, USE_VAbv, USE_VPst,
	USE_H, USE_O, USE_R, USE_R, USE_O, USE_O, USE_O, USE_O,
	USE_O, USE_FMBlw, USE_CMBlw, USE_VAbv, USE_VBlw, USE_O, USE_VPre, USE_VMAbv,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N,
}

// Sinhala Archaic Numbers (U+111E1-U+111F4)
var useTable111E1 = [20]USECategory{
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N, USE_N, USE_N,
}

// Khojki (U+11200-U+11241)
var useTable11200 = [66]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_O, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_VPst, USE_VPst, USE_VPst, USE_VBlw,
	USE_VAbv, USE_VAbv, USE_VPst, USE_VPst, USE_VMAbv, USE_H, USE_CMAbv, USE_CMAbv,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_VMAbv, USE_B,
	USE_B, USE_VBlw,
}

// Multani (U+11280-U+112A8)
var useTable11280 = [41]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_O,
	USE_B, USE_O, USE_B, USE_B, USE_B, USE_B, USE_O, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_O, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B,
}

// Khudawadi (U+112B0-U+112F9)
var useTable112B0 = [74]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_VMAbv,
	USE_VPst, USE_VPre, USE_VPst, USE_VBlw, USE_VBlw, USE_VAbv, USE_VAbv, USE_VAbv,
	USE_VAbv, USE_CMBlw, USE_VBlw, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N,
}

// Grantha (U+11300-U+11374)
var useTable11300 = [117]USECategory{
	USE_VMAbv, USE_VMAbv, USE_VMPst, USE_VMPst, USE_O, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_O, USE_O, USE_B,
	USE_B, USE_O, USE_O, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_O, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_O, USE_B, USE_B, USE_O, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_O, USE_CMBlw, USE_CMBlw, USE_O, USE_VPst, USE_VPst,
	USE_VAbv, USE_VPst, USE_VPst, USE_VPst, USE_VPst, USE_O, USE_O, USE_VPre,
	USE_VPre, USE_O, USE_O, USE_VPst, USE_VPst, USE_H, USE_O, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_VPst,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_VM, USE_VM,
	USE_B, USE_B, USE_VPst, USE_VPst, USE_O, USE_O, USE_VMAbv, USE_VMAbv,
	USE_VMAbv, USE_VMAbv, USE_VMAbv, USE_VMAbv, USE_VMAbv, USE_O, USE_O, USE_O,
	USE_VMAbv, USE_VMAbv, USE_VMAbv, USE_VMAbv, USE_VMAbv,
}

// Tulu-Tigalari (U+11380-U+113E2)
var useTable11380 = [99]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_O, USE_B, USE_O, USE_O, USE_B, USE_O,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_O, USE_O,
	USE_VPst, USE_VPst, USE_VPst, USE_VBlw, USE_VBlw, USE_VBlw, USE_VBlw, USE_VBlw,
	USE_VBlw, USE_O, USE_VPre, USE_O, USE_O, USE_VPre, USE_O, USE_VPst,
	USE_VPst, USE_VPst, USE_VMPst, USE_O, USE_VMPst, USE_VMPst, USE_VAbv, USE_VPst,
	USE_IS, USE_R, USE_CMBlw, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_O, USE_VMAbv, USE_VMBlw,
}

// Newa (U+11400-U+11461)
var useTable11400 = [98]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_VPst, USE_VPre, USE_VPst,
	USE_VBlw, USE_VBlw, USE_VBlw, USE_VBlw, USE_VBlw, USE_VBlw, USE_VAbv, USE_VAbv,
	USE_VPst, USE_VPst, USE_H, USE_VMAbv, USE_VMAbv, USE_VMPst, USE_CMBlw, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N, USE_O, USE_O, USE_O, USE_O, USE_FMAbv, USE_VM,
	USE_CS, USE_CS,
}

// Tirhuta (U+11481-U+114D9)
var useTable11481 = [89]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_VPst,
	USE_VPre, USE_VPst, USE_VBlw, USE_VBlw, USE_VBlw, USE_VBlw, USE_VBlw, USE_VBlw,
	USE_VPre, USE_VAbv, USE_VAbv, USE_VPst, USE_VPst, USE_VPst, USE_VMAbv, USE_VMAbv,
	USE_VMPst, USE_H, USE_CMBlw, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_N,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N,
}

// Siddham (U+11580-U+115DD)
var useTable11580 = [94]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_VPst,
	USE_VPre, USE_VPst, USE_VBlw, USE_VBlw, USE_VBlw, USE_VBlw, USE_O, USE_O,
	USE_VPre, USE_VAbv, USE_VPst, USE_VPst, USE_VMAbv, USE_VMAbv, USE_VMPst, USE_H,
	USE_CMBlw, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_B, USE_B, USE_B, USE_B, USE_VBlw, USE_VBlw,
}

// Modi (U+11600-U+11659)
var useTable11600 = [90]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_VPst, USE_VPst, USE_VPst, USE_VBlw, USE_VBlw, USE_VBlw, USE_VBlw, USE_VBlw,
	USE_VBlw, USE_VAbv, USE_VAbv, USE_VPst, USE_VPst, USE_VMAbv, USE_VMPst, USE_H,
	USE_VAbv, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N,
}

// Takri (U+11680-U+116C9)
var useTable11680 = [74]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_VMAbv, USE_VMPst, USE_VAbv, USE_VPre, USE_VPst,
	USE_VBlw, USE_VBlw, USE_VAbv, USE_VAbv, USE_VAbv, USE_VAbv, USE_H, USE_CMBlw,
	USE_B, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N,
}

// Myanmar Extended-C (U+116D0-U+116E3)
var useTable116D0 = [20]USECategory{
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N, USE_N, USE_N,
}

// Ahom (U+11700-U+11746)
var useTable11700 = [71]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_O, USE_O, USE_MBlw, USE_MBlw, USE_MAbv,
	USE_VPst, USE_VPst, USE_VAbv, USE_VAbv, USE_VBlw, USE_VBlw, USE_VPre, USE_VAbv,
	USE_VBlw, USE_VAbv, USE_VAbv, USE_VAbv, USE_O, USE_O, USE_O, USE_O,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N, USE_N, USE_N, USE_O, USE_O, USE_O, USE_O,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
}

// Dogra (U+11800-U+1183A)
var useTable11800 = [59]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_VPst, USE_VPre, USE_VPst, USE_VBlw,
	USE_VBlw, USE_VBlw, USE_VBlw, USE_VAbv, USE_VAbv, USE_VAbv, USE_VAbv, USE_VMAbv,
	USE_VMPst, USE_H, USE_CMBlw,
}

// Dives Akuru (U+11900-U+11959)
var useTable11900 = [90]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_O,
	USE_O, USE_B, USE_O, USE_O, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_O, USE_B, USE_B, USE_O,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_VPst, USE_VPst, USE_VPst, USE_VPst, USE_VPst, USE_VPre, USE_O, USE_VPre,
	USE_VPst, USE_O, USE_O, USE_VMAbv, USE_VMAbv, USE_VPst, USE_IS, USE_R,
	USE_MPst, USE_R, USE_MPst, USE_CMBlw, USE_O, USE_O, USE_O, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N,
}

// Nandinagari (U+119A0-U+119E4)
var useTable119A0 = [69]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_O, USE_O, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_VPst, USE_VPre, USE_VPst, USE_VBlw, USE_VBlw, USE_VBlw, USE_VBlw,
	USE_O, USE_O, USE_VAbv, USE_VAbv, USE_VPst, USE_VPst, USE_VMPst, USE_VMPst,
	USE_H, USE_O, USE_O, USE_O, USE_VPre,
}

// Zanabazar Square (U+11A00-U+11A47)
var useTable11A00 = [72]USECategory{
	USE_B, USE_VAbv, USE_VBlw, USE_VBlw, USE_VAbv, USE_VAbv, USE_VAbv, USE_VAbv,
	USE_VAbv, USE_VAbv, USE_VBlw, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_FMBlw, USE_VBlw, USE_VMAbv, USE_VMAbv, USE_VMAbv,
	USE_VMAbv, USE_VMPst, USE_CS, USE_MBlw, USE_MBlw, USE_MBlw, USE_MBlw, USE_GB,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_GB, USE_O, USE_IS,
}

// Soyombo (U+11A50-U+11A9D)
var useTable11A50 = [78]USECategory{
	USE_B, USE_VAbv, USE_VBlw, USE_VBlw, USE_VAbv, USE_VAbv, USE_VAbv, USE_VPst,
	USE_VPst, USE_VBlw, USE_VBlw, USE_VBlw, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_R, USE_R, USE_R, USE_R,
	USE_R, USE_R, USE_FBlw, USE_FBlw, USE_FBlw, USE_FBlw, USE_FBlw, USE_FBlw,
	USE_FBlw, USE_FBlw, USE_FBlw, USE_FBlw, USE_FBlw, USE_FBlw, USE_VMAbv, USE_VMPst,
	USE_CMAbv, USE_IS, USE_O, USE_O, USE_O, USE_O,
}

// Bhaiksuki (U+11C00-U+11C6C)
var useTable11C00 = [109]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_O, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_VPst,
	USE_VAbv, USE_VAbv, USE_VBlw, USE_VBlw, USE_VBlw, USE_VBlw, USE_VBlw, USE_O,
	USE_VAbv, USE_VAbv, USE_VAbv, USE_VAbv, USE_VMAbv, USE_VMAbv, USE_VMPst, USE_H,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N, USE_N, USE_N, USE_N,
}

// Marchen (U+11C72-U+11CB6)
var useTable11C72 = [69]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_O, USE_O,
	USE_SUB, USE_SUB, USE_SUB, USE_SUB, USE_SUB, USE_SUB, USE_SUB, USE_SUB,
	USE_SUB, USE_SUB, USE_SUB, USE_SUB, USE_SUB, USE_SUB, USE_SUB, USE_SUB,
	USE_SUB, USE_SUB, USE_SUB, USE_SUB, USE_SUB, USE_SUB, USE_O, USE_SUB,
	USE_SUB, USE_SUB, USE_SUB, USE_SUB, USE_SUB, USE_SUB, USE_VBlw, USE_VPre,
	USE_VBlw, USE_VAbv, USE_VPst, USE_VMAbv, USE_VMAbv,
}

// Masaram Gondi (U+11D00-U+11D59)
var useTable11D00 = [90]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_O,
	USE_B, USE_B, USE_O, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_VAbv, USE_VAbv, USE_VAbv, USE_VAbv, USE_VAbv, USE_VBlw, USE_O,
	USE_O, USE_O, USE_VAbv, USE_O, USE_VAbv, USE_VAbv, USE_O, USE_VAbv,
	USE_VMAbv, USE_VMAbv, USE_CMBlw, USE_VAbv, USE_VBlw, USE_IS, USE_R, USE_MBlw,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N,
}

// Gunjala Gondi (U+11D60-U+11DA9)
var useTable11D60 = [74]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_O, USE_B,
	USE_B, USE_O, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_VPst, USE_VPst, USE_VPst, USE_VPst, USE_VPst, USE_O,
	USE_VAbv, USE_VAbv, USE_O, USE_VPst, USE_VPst, USE_VMAbv, USE_VMPst, USE_IS,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N,
}

// Makasar (U+11EE0-U+11EF6)
var useTable11EE0 = [23]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_GB, USE_VAbv, USE_VBlw, USE_VPre, USE_VPst,
}

// Kawi (U+11F00-U+11F5A)
var useTable11F00 = [91]USECategory{
	USE_VMAbv, USE_VMAbv, USE_R, USE_VMPst, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_O, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_VPst, USE_VPst, USE_VAbv, USE_VAbv,
	USE_VBlw, USE_VBlw, USE_VBlw, USE_O, USE_O, USE_O, USE_VPre, USE_VPre,
	USE_VAbv, USE_VPst, USE_IS, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O, USE_O,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N, USE_CMAbv,
}

// Gurung Khema (U+16100-U+16139)
var useTable16100 = [58]USECategory{
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_VAbv, USE_VAbv,
	USE_VAbv, USE_VAbv, USE_VAbv, USE_VAbv, USE_VAbv, USE_VAbv, USE_VAbv, USE_VAbv,
	USE_VAbv, USE_VAbv, USE_MPre, USE_MPre, USE_MPst, USE_VMAbv, USE_MBlw, USE_VBlw,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N,
}

// Kirat Rai (U+16D40-U+16D79)
var useTable16D40 = [58]USECategory{
	USE_VMPst, USE_VMPst, USE_VMPst, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B, USE_B,
	USE_B, USE_B, USE_B, USE_VPst, USE_VPst, USE_VPst, USE_VPst, USE_VPst,
	USE_VPst, USE_VPst, USE_VPst, USE_VPst, USE_VPst, USE_O, USE_O, USE_O,
	USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N, USE_N,
	USE_N, USE_N,
}

// isUSEScript returns true if the codepoint belongs to a USE-handled script.
// These scripts use the Universal Shaping Engine instead of script-specific shapers.
func isUSEScript(cp Codepoint) bool {
	// Ahom
	if cp >= 0x11700 && cp <= 0x11746 {
		return true
	}
	// Balinese
	if cp >= 0x1B00 && cp <= 0x1B59 {
		return true
	}
	// Batak
	if cp >= 0x1BC0 && cp <= 0x1BF3 {
		return true
	}
	// Bengali
	if cp >= 0x0980 && cp <= 0x09FE {
		return true
	}
	// Bhaiksuki
	if cp >= 0x11C00 && cp <= 0x11C6C {
		return true
	}
	// Brahmi
	if cp >= 0x11000 && cp <= 0x1107F {
		return true
	}
	// Buginese
	if cp >= 0x1A00 && cp <= 0x1A1B {
		return true
	}
	// Buhid
	if cp >= 0x1740 && cp <= 0x1753 {
		return true
	}
	// Chakma
	if cp >= 0x11100 && cp <= 0x11147 {
		return true
	}
	// Cham
	if cp >= 0xAA00 && cp <= 0xAA59 {
		return true
	}
	// Devanagari
	if cp >= 0x0900 && cp <= 0x097F {
		return true
	}
	if cp >= 0xA8E0 && cp <= 0xA8FF {
		return true
	}
	// Dives_Akuru
	if cp >= 0x11900 && cp <= 0x11959 {
		return true
	}
	// Dogra
	if cp >= 0x11800 && cp <= 0x1183A {
		return true
	}
	// Grantha
	if cp >= 0x11300 && cp <= 0x11374 {
		return true
	}
	// Gujarati
	if cp >= 0x0A81 && cp <= 0x0AFF {
		return true
	}
	// Gunjala_Gondi
	if cp >= 0x11D60 && cp <= 0x11DA9 {
		return true
	}
	// Gurmukhi
	if cp >= 0x0A01 && cp <= 0x0A75 {
		return true
	}
	// Gurung_Khema
	if cp >= 0x16100 && cp <= 0x16139 {
		return true
	}
	// Hanunoo
	if cp >= 0x1720 && cp <= 0x1734 {
		return true
	}
	// Javanese
	if cp >= 0xA980 && cp <= 0xA9D9 {
		return true
	}
	// Kaithi
	if cp >= 0x11080 && cp <= 0x110C2 {
		return true
	}
	// Kannada
	if cp >= 0x0C80 && cp <= 0x0CF3 {
		return true
	}
	// Kawi
	if cp >= 0x11F00 && cp <= 0x11F5A {
		return true
	}
	// Kayah_Li
	if cp >= 0xA900 && cp <= 0xA92D {
		return true
	}
	// Kharoshthi
	if cp >= 0x10A00 && cp <= 0x10A48 {
		return true
	}
	// Khmer
	if cp >= 0x1780 && cp <= 0x17E9 {
		return true
	}
	// Khojki
	if cp >= 0x11200 && cp <= 0x11241 {
		return true
	}
	// Khudawadi
	if cp >= 0x112B0 && cp <= 0x112F9 {
		return true
	}
	// Kirat_Rai
	if cp >= 0x16D40 && cp <= 0x16D79 {
		return true
	}
	// Lepcha
	if cp >= 0x1C00 && cp <= 0x1C4F {
		return true
	}
	// Limbu
	if cp >= 0x1900 && cp <= 0x194F {
		return true
	}
	// Mahajani
	if cp >= 0x11150 && cp <= 0x11173 {
		return true
	}
	// Makasar
	if cp >= 0x11EE0 && cp <= 0x11EF6 {
		return true
	}
	// Malayalam
	if cp >= 0x0D00 && cp <= 0x0D7F {
		return true
	}
	// Marchen
	if cp >= 0x11C72 && cp <= 0x11CB6 {
		return true
	}
	// Masaram_Gondi
	if cp >= 0x11D00 && cp <= 0x11D59 {
		return true
	}
	// Meetei_Mayek
	if cp >= 0xAAE0 && cp <= 0xABF9 {
		return true
	}
	// Modi
	if cp >= 0x11600 && cp <= 0x11659 {
		return true
	}
	// Multani
	if cp >= 0x11280 && cp <= 0x112A8 {
		return true
	}
	// Myanmar
	if cp >= 0x1000 && cp <= 0x109D {
		return true
	}
	if cp >= 0xA9E0 && cp <= 0xAA7F {
		return true
	}
	if cp >= 0x116D0 && cp <= 0x116E3 {
		return true
	}
	// Nandinagari
	if cp >= 0x119A0 && cp <= 0x119E4 {
		return true
	}
	// New_Tai_Lue
	if cp >= 0x1980 && cp <= 0x19DA {
		return true
	}
	// Newa
	if cp >= 0x11400 && cp <= 0x11461 {
		return true
	}
	// Oriya
	if cp >= 0x0B01 && cp <= 0x0B71 {
		return true
	}
	// Phags_Pa
	if cp >= 0xA840 && cp <= 0xA873 {
		return true
	}
	// Rejang
	if cp >= 0xA930 && cp <= 0xA953 {
		return true
	}
	// Saurashtra
	if cp >= 0xA880 && cp <= 0xA8D9 {
		return true
	}
	// Sharada
	if cp >= 0x11180 && cp <= 0x111D9 {
		return true
	}
	if cp >= 0x11B60 && cp <= 0x11B67 {
		return true
	}
	// Siddham
	if cp >= 0x11580 && cp <= 0x115DD {
		return true
	}
	// Sinhala
	if cp >= 0x0D81 && cp <= 0x0DF3 {
		return true
	}
	if cp >= 0x111E1 && cp <= 0x111F4 {
		return true
	}
	// Soyombo
	if cp >= 0x11A50 && cp <= 0x11A9D {
		return true
	}
	// Sundanese
	if cp >= 0x1B80 && cp <= 0x1BBF {
		return true
	}
	// Syloti_Nagri
	if cp >= 0xA800 && cp <= 0xA82C {
		return true
	}
	// Tagalog
	if cp >= 0x1700 && cp <= 0x171F {
		return true
	}
	// Tagbanwa
	if cp >= 0x1760 && cp <= 0x1773 {
		return true
	}
	// Tai_Le
	if cp >= 0x1950 && cp <= 0x1974 {
		return true
	}
	// Tai_Tham
	if cp >= 0x1A20 && cp <= 0x1A99 {
		return true
	}
	// Tai_Viet
	if cp >= 0xAA80 && cp <= 0xAAC2 {
		return true
	}
	// Takri
	if cp >= 0x11680 && cp <= 0x116C9 {
		return true
	}
	// Tamil
	if cp >= 0x0B82 && cp <= 0x0BEF {
		return true
	}
	// Telugu
	if cp >= 0x0C00 && cp <= 0x0C6F {
		return true
	}
	// Tibetan
	if cp >= 0x0F20 && cp <= 0x0FC6 {
		return true
	}
	// Tirhuta
	if cp >= 0x11481 && cp <= 0x114D9 {
		return true
	}
	// Tulu_Tigalari
	if cp >= 0x11380 && cp <= 0x113E2 {
		return true
	}
	// Zanabazar_Square
	if cp >= 0x11A00 && cp <= 0x11A47 {
		return true
	}
	return false
}
